refactor: General code improvement
yurixander/mirage pull request #16
Opened 2024-03-14 17:03 UTC by criss8X

1. Optimicé la función de normalizar nombres para que use filter 
2. Revise en que casos de uso la key debería usar index, y en que otros debería ser algo mas único.
3. Respecto a la función getImage en lugar de retornar undefined cuando no obtiene la imagen, ahora retorna null, ya que null conviene más por su significado de ausencia de un valor.

2024-03-14 17:22 UTC, yurixander requested changes

2024-03-14 17:22 UTC, yurixander commented on src/components/ChatContainer.tsx
> +            key={(message.data as UnreadIndicatorProperties).lastReadEventId}
Evitar usar `as` lo mas posible, busca porque los mensajes no tienen tipo `EventMessageProperties[]`? `as` basicamente le dices al compilador: 'Ignora esto.'

2024-03-14 17:22 UTC, yurixander commented on src/components/ChatContainer.tsx
> +            key={(message.data as UnreadIndicatorProperties).lastReadEventId}
Otra cosa, el key debe ser unico, asi que el contenido quizas no sea unico. Ve a ver si hay otra propiedad que es unica, algo como un `id`

2024-03-14 17:22 UTC, yurixander commented on src/components/ImageMessage.tsx
>  }
Usa `interface` y `extends` porque `type` y `&` re-emplaza propiedades sin dar error.

2024-03-14 17:22 UTC, yurixander commented on src/components/Navigation.tsx
> +        key={server.roomId}
👍🏼

2024-03-14 17:22 UTC, yurixander commented on src/components/Roster.tsx
> +        .map(member => <RosterUser key={member.userId} {...member} />),
Si se desplega, que pasa con la propiedad `userId`? Se acepta en los props del `RosterUser`?

2024-03-14 17:22 UTC, yurixander commented on src/utils/util.ts
> +  return [...displayName]
Usa `displayName.split("")` que es mas reconocido y claro

2024-03-14 18:48 UTC, yurixander requested changes

2024-03-14 18:48 UTC, yurixander commented on src/components/MessageContainer.tsx
> +export interface MessageBaseProps {
Este no, solo los que usan `&` para extender

2024-03-14 18:48 UTC, yurixander commented on src/components/TextMessage.tsx
> +export interface TextMessageProps extends MessageBaseProperties {}
Deshazte de este si no tiene nada. Por ahora, solo usa `MessageBaseProperties` directamente, y le puedes cambiar el nombre a `MessageBaseProps`

2024-03-15 03:36 UTC, yurixander requested changes

2024-03-15 03:36 UTC, yurixander commented on src/components/ChatContainer.tsx
> +            key={message.data.lastReadEventId}
No me convence esto

2024-03-15 03:36 UTC, yurixander commented on src/components/MessageContainer.tsx
> +  authorAvatarUrl: string | null
En los props es aceptable y preferible usar undefined para significar un prop opcional

2024-03-16 13:56 UTC, yurixander requested changes

2024-03-16 13:56 UTC, yurixander commented on src/utils/util.ts
> +export type ImageUploadedInfo = {
Solo se pueden subir imágenes en este caso?

2024-03-16 14:51 UTC, criss8X commented on src/utils/util.ts
> +export type ImageUploadedInfo = {
Si, lo cambie porque estaba mal el nombre con respecto a su funcionalidad, ya que en un principio el objetivo de esa función era algo global de enviar cualquier archivo pero me di cuenta que la forma en enviar una imagen tiene variación, hasta que no pruebe el envío de archivos o audios verificando que hayan cosas en común no sería inteligente tener un nombre tan abarcador.

2024-03-16 15:17 UTC, criss8X commented on src/components/UserProfile.tsx
>        <Avatar size={isLarge ? 60 : 40} square name={text} variant="beam" />
Ese componente Avatar es el de boring-avatars, el otro componente Avatar que tenemos custom abra que globalizarlo mas, cambiarle el nombre evitar conflictos con boring-avatars.

2024-03-16 16:21 UTC, yurixander requested changes

2024-03-16 16:21 UTC, yurixander commented on src/components/ChatContainer.tsx
> +          <UnreadIndicator key={"unread-indicator"} {...message.data} />
Quitale los `{` `}`

2024-03-16 23:47 UTC, yurixander requested changes

2024-03-16 23:47 UTC, yurixander commented on src/components/Avatar.tsx
> +        isRounded && "rounded-[50%]"
`rounded-full`?

2024-03-16 23:47 UTC, yurixander commented on src/components/ServerListItem.tsx
> +          displayName={"Margaret Sanger"}
Quítale el {}

2024-03-16 23:47 UTC, yurixander commented on src/components/TypingIndicator.tsx
> +          <div className="size-[30px] object-contain">
`size-8`?

2024-03-17 13:43 UTC, yurixander approved these changes

2024-03-17 21:55 UTC, lazaroysr96 approved these changes

2024-03-17 22:42 UTC, lazaroysr96 requested changes

2024-03-17 22:42 UTC, lazaroysr96 commented on src/utils/util.ts
Revisa en la linea 320, al parecer hay algo que interfiere con el funcionamiento del StoryBook
![errr](https://github.com/yurixander/mirage/assets/156694602/ed8f714d-b7c9-4c0e-93e3-71ce7d28918d)

2024-03-17 23:24 UTC, lazaroysr96 commented on src/utils/util.ts
0xFF por 0xff

2024-03-18 15:11 UTC, criss8X commented on src/components/RadioGroup.tsx
Entiendo, crearé una nueva tarea para ello.

2024-03-18 15:22 UTC, lazaroysr96 approved these changes

2024-03-18 15:31 UTC, merged