refactor: Prefer use RoomSummary for  ´useActiveRoom´ hook
yurixander/mirage pull request #17
Opened 2024-03-17 13:20 UTC by criss8X

El tipo RoomSummary precisamente está para ser usado en lugares que desees acceder a cierta información de la Room en lugar de obtener el objeto Room completo. En el caso de ´ChatContainer´ que muestra cierta información al usuario de la Room como el nombre no hace falta obtener un objeto completo de Room.

2024-03-18 15:40 UTC, yurixander requested changes

2024-03-18 15:40 UTC, yurixander commented on src/components/ChatContainer.tsx
> +          <UnreadIndicator key={v4()} {...message.data} />
Estos cambios como que son antiguos? Revisa bien porque sino si se incorpora esto básicamente revierten tus cambios en el otro PR. Creo que es esta parts nada más 🤔.

2024-03-18 15:41 UTC, criss8X commented on src/components/ChatContainer.tsx
> +          <UnreadIndicator key={v4()} {...message.data} />
Si son antiguos, como eso estaba arreglandose en la otra PR que fue la que se subio ahora

2024-03-18 15:42 UTC, criss8X commented on src/components/ChatContainer.tsx
> +          <UnreadIndicator key={v4()} {...message.data} />
Yo empecé a trabajar en esto en lo que se revisaba la primer PR

2024-03-19 14:09 UTC, yurixander requested changes

2024-03-19 14:26 UTC, yurixander submitted a review, later dismissed

2024-03-20 03:11 UTC, lazaroysr96 approved these changes

2024-03-20 03:17 UTC, lazaroysr96 requested changes

2024-03-20 03:17 UTC, lazaroysr96 commented on src/components/MessageContainer.tsx
Este archivo esta mostrando una especie de conflicto con otra raíz o  algo así, revisa por ahí si hay que subir algún cambio echo en una raíz mas reciente o algo así.

2024-03-21 17:37 UTC, yurixander approved these changes

2024-03-21 17:37 UTC, merged