Lazaroysr96/Implementación de la interfaz para CreateRoom
yurixander/mirage pull request #20
Opened 2024-03-17 21:37 UTC by lazaroysr96

Implementación de la interfaz del componente **CreateRoom**

**Dropdown** confeccionado en base al elemento **select**, el funcionamiento de este componente es básicamente similar al de los RadioButton, a cada elemento se le puede pasar un:

- **label**: _Texto que mostrará al usuario_

- **value**: _Valor que contendrá para casos de formularios._

- **onClick**: _Para implementar alguna lógica al seleccionarlo._

Quedo a la espera de sus opiniones.

2024-03-17 21:46 UTC, yurixander requested changes

2024-03-17 21:46 UTC, yurixander commented on src/components/CreateRoom.tsx
> +    <div className="flex flex-col gap-4 rounded-[10px] border-[1px] border-solid border-neutral-300 bg-slate-50 p-5 shadow-sm">
Usa simplemente `border` en vez de `border-[1px]`. Siempre tratar de evitar usar valores arbitrarios en Tailwind `-[]`.

Para el rounded, prueba algo como `rounded-xl` o `rounded-lg`. [Date un vistazo en la página de documentación de Tailwind](https://tailwindcss.com/docs/installation), ahí te dice los valores posibles para cada propiedad.

2024-03-17 21:46 UTC, yurixander commented on src/components/CreateRoom.tsx
> +    <div className="flex flex-col gap-4 rounded-[10px] border-[1px] border-solid border-neutral-300 bg-slate-50 p-5 shadow-sm">
El `border-solid` creo que sobra también, por defecto ya es `solid`.

2024-03-17 21:46 UTC, yurixander commented on src/components/CreateRoom.tsx
> +        <Input placeholder="Name"></Input>
Usa el estilo `<Input ... />` para los componentes sin hijos.

2024-03-17 21:46 UTC, yurixander commented on src/components/Dropdown.tsx
> +}
Por ahora es aceptable, pero más adelante en vez de pasar las opciones por props, las opciones en si deberían ser componentes. Ejemplo:
```tsx
<Dropdown>
  <DropdownOption label={...} value={...} />
  ...
</Dropdown>
```

2024-03-17 23:47 UTC, lazaroysr96 commented on src/components/CreateRoom.tsx
> +    <div className="flex flex-col gap-4 rounded-[10px] border-[1px] border-solid border-neutral-300 bg-slate-50 p-5 shadow-sm">
utilizaré rounded-lg que son 8px, estaba utilizando el mismo rounded de los Inputs

2024-03-18 00:01 UTC, criss8X commented on src/components/Dropdown.tsx
> +      <select className="flex items-center rounded-[10px] border-[1px] border-solid border-neutral-300 bg-white p-2">
Quizás aquí se pueda usar rounded-lg (8px) o rounded-xl (12px) el Dropdown probablemente rounded-lg para hacerlo consistente junto con ContextMenu.

2024-03-18 00:09 UTC, criss8X commented on src/stories/dropdown.stories.tsx
> +}
Esto en sí no esta mal pero en los archivos stories pasamos los argumentos desde arriba y seria ideal mantener dicha consistencia, puedes apoyarte en otros archivos stories o usar los templates (si escribes storyProps en un archivo en blanco y pulsas enter con el autocompletado te sacara un template listo para que solo pongas el nombre y argumentos.
![Captura de pantalla 2024-03-17 200616](https://github.com/yurixander/mirage/assets/100869331/87c4ff97-67c7-4cbc-8db1-000a438448fb)


Algo asi te debería quedar: 

```
type Story = StoryObj<typeof Dropdown>

const meta: Meta<typeof Dropdown> = {
  component: Dropdown,
}
const render = (args: Props) => <Dropdown {...args} />

export const Default: Story = {
  render,
  args: {// Aquí iran las props},
}
```

2024-03-18 00:19 UTC, criss8X commented on src/stories/dropdown.stories.tsx
> +export default meta
Esto en sí no esta mal pero en los archivos stories pasamos los argumentos desde arriba y seria ideal mantener dicha consistencia, puedes apoyarte en otros archivos stories o usar los templates (si escribes storyProps en un archivo en blanco y pulsas enter con el autocompletado te sacara un template listo para que solo pongas el nombre y argumentos.
![Captura de pantalla 2024-03-17 200616](https://github.com/yurixander/mirage/assets/100869331/87c4ff97-67c7-4cbc-8db1-000a438448fb)


Algo asi te debería quedar: 

```
type Story = StoryObj<typeof Dropdown>

const meta: Meta<typeof Dropdown> = {
  component: Dropdown,
}
const render = (args: Props) => <Dropdown {...args} />

export const Default: Story = {
  render,
  args: {// Aquí iran las props},
}
```

2024-03-18 00:31 UTC, criss8X commented on src/stories/dropdown.stories.tsx
Esto en sí no esta mal pero en los archivos stories pasamos los argumentos desde arriba y seria ideal mantener dicha consistencia, puedes apoyarte en otros archivos stories o usar los templates (si escribes storyProps en un archivo en blanco y pulsas enter con el autocompletado te sacara un template listo para que solo pongas el nombre y argumentos.
![Captura de pantalla 2024-03-17 200616](https://github.com/yurixander/mirage/assets/100869331/87c4ff97-67c7-4cbc-8db1-000a438448fb)


Algo asi te debería quedar: 

```
type Story = StoryObj<typeof Dropdown>

const meta: Meta<typeof Dropdown> = {
  component: Dropdown,
}
const render = (args: Props) => <Dropdown {...args} />

export const Default: Story = {
  render,
  args: {// Aquí iran las props},
}
```

2024-03-18 00:31 UTC, criss8X commented on src/components/Dropdown.tsx
> +      <select className="flex items-center rounded-[10px] border-[1px] border-solid border-neutral-300 bg-white p-2">
Quizás aquí se pueda usar rounded-lg (8px) o rounded-xl (12px) probablemente rounded-lg para hacerlo consistente junto con ContextMenu.

2024-03-18 03:07 UTC, yurixander requested changes

2024-03-18 03:07 UTC, yurixander commented on src/components/Dropdown.tsx
> +    </>
No se necesita usa `<></>` si solamente estar retornando un solo elemento.

2024-03-18 04:19 UTC, yurixander approved these changes

2024-03-18 12:32 UTC, criss8X approved these changes

2024-03-18 12:32 UTC, merged