feat: implement dark mode in reply message
yurixander/mirage pull request #203
Opened 2024-10-24 17:35 UTC by lazaroysr96

## Título breve de lo que hiciste

### Progreso:

 - [ ] Integrar el componente a la lógica.
 - [ ] Implementar aria labels y accesibilidad (key ect...).
 - [ ] Verificar responsividad del componente usando dev tools.
 - [ ] Crear historia de storybook
 - [ ] Agregar hotkeys, tab index y event listeners de Enter para comprobar el componente en el teclado.
 - [ ] Agregar variante dark/oscuro para los componentes nuevos creados.

2024-10-26 18:33 UTC, criss8X requested changes

2024-10-26 18:33 UTC, criss8X commented on src/components/ReplyMessage.tsx
> +      type="button"
se te fue un type="button" redundante

2024-10-26 18:33 UTC, criss8X commented on src/components/ReplyMessage.tsx
> +          showTooltip("Quoted MessageId is undefined", true)
espacio entre showTooltip y return 

En el mensaje del tooltip tratar de poner informacion mas para el usuario como No se encuentra o No se encontro este mensaje pero en ingles

2024-10-26 18:33 UTC, criss8X commented on src/components/ReplyMessage.tsx
> +      <Text className="line-clamp-1 max-w-40 shrink-0 text-xs">
Porque un text-xs si el componente Text maneja esas cosas con el size? para que sea responsivo

2024-10-26 18:33 UTC, criss8X commented on src/components/ReplyMessage.tsx
> +      <Text
En lugar de font-bold hay algo una prop de Text que es el peso weight para poner en bold
En lugar de text-xs usar el size correspondiente para que la responsividad sea manejada por Text de forma generica

2024-10-26 18:33 UTC, criss8X commented on src/components/ReplyMessage.tsx
> +            <TooltipContent aria-hidden>{quotedText}</TooltipContent>
porque el contenido del Tooltip esta hidden si no hay aria-label en otro lado?

2024-10-26 19:37 UTC, lazaroysr96 commented on src/components/ReplyMessage.tsx
> +      type="button"
No exactamente, lo puse ahí con toda intención debido a que había un linter avisándome de que debía especificar el type.

2024-10-27 20:33 UTC, criss8X approved these changes

2024-10-27 20:34 UTC, merged