feat: Implement lazy load of members
yurixander/mirage pull request #206
Opened 2024-10-27 22:42 UTC by criss8X

## Implementar la carga diferida que porvee matrix con el diseño del Roster

En este PR no mucho que explicar es una carga a medida que bajas usando la que provee matrix, hasta que se asegure el diseño y se pueda hacer una mejor implementacion con el diseño

2024-11-01 12:42 UTC, yurixander requested changes

2024-11-01 12:42 UTC, yurixander commented on src/components/ui/scroll-area.tsx
> +  React.useEffect(() => {
Este estilo React.X lo estamos usando en todos los otros lugares? Creo que usar useEffect es mas simple, sin el React.

2024-11-01 12:42 UTC, yurixander commented on src/containers/Roster/hooks/useRoomMembers.ts
> +
```suggestion
```

2024-11-01 12:42 UTC, yurixander commented on src/hooks/util/useIntersection.ts
> +  E extends HTMLElement = HTMLDivElement,
Cambiar C -> Container y E -> Element, solo usar T cuando hay un solo tipo generico, de contrario, siempre poner nombres normales

2024-11-01 12:42 UTC, yurixander commented on src/utils/members.ts
> +
```suggestion
```

2024-11-02 02:36 UTC, criss8X commented on src/components/ui/scroll-area.tsx
> +  React.useEffect(() => {
Ese estilo se encontraba en los componentes de Shadcn que traiamos y modificabamos pero ya lo reparo

2024-11-03 18:20 UTC, yurixander requested changes

2024-11-03 18:20 UTC, yurixander commented on src/containers/Roster/hooks/useRoomMembers.ts
> +    }
Que significa esta condicion? Un comentario breve puede ayudar aqui

2024-11-03 18:20 UTC, yurixander commented on src/containers/Roster/hooks/useRoomMembers.ts
> +              status: "success",
Este estado es de nosotros? Si ese es el caso, siempre preferir enums en vez de strings cuando sea posible

2024-11-03 18:20 UTC, yurixander commented on src/containers/Roster/hooks/useRoomMembers.ts
> +      }
Esto nunca deberia pasar? Si es el caso, mejor seria usar un assert

2024-11-03 18:58 UTC, criss8X commented on src/containers/Roster/hooks/useRoomMembers.ts
> +      }
Esto si puede ocurrir, se callo la conexion al usuario y le da click en el boton pues le muestra al usuario un tooltip que dice eso

2024-11-03 19:01 UTC, lazaroysr96 approved these changes
Solo me preocupa el rendimiento en cuanto al consumo de recursos que pueda tener cargar todos los miembros de una room teniendo en cuenta que las salas en matrix pueden contener un gran número de miembros, por lo demás, todo bien, solo resta resolver los comentarios pendientes.

2024-11-05 13:30 UTC, yurixander approved these changes

2024-11-06 14:30 UTC, merged