feat: Implement ´DirectMessageModal´ for SidebarActions component
yurixander/mirage pull request #22
Opened 2024-03-21 18:28 UTC by criss8X

Componente donde se gestiona el buscar personas para iniciar una conversación, o simplemente iniciar una conversación con alguien que tengas en tu lista de chats directos.

2024-03-21 19:00 UTC, yurixander commented on src/hooks/matrix/useSidebarActions.ts
> +}
También, estos hooks pegados a componentes de UI, metelos en una carpeta junta con el componente en si en vez de tenerlos dentro de la carpeta hooks; la carpeta hooks solo debería contener hooks comunes/compartidos. Si un hook es específico/ayudante a un componente, hazle una carpeta en donde está el componente y mete ambos en esa carpeta.

2024-03-21 19:03 UTC, yurixander commented on src/hooks/matrix/useUserSearch.ts
> +        return
Línea nueva separar

2024-03-21 19:03 UTC, yurixander commented on src/hooks/matrix/useUserSearch.ts
> +      }
En que caso sería esto undefined, que significa ser undefined aqui? Explica usando comentario

2024-03-21 19:05 UTC, yurixander commented on src/hooks/matrix/useUserSearch.ts
> +    }
Timer usado para que razón? Usa el nombre "debounce" o "debounced"

2024-03-21 19:05 UTC, yurixander commented on src/stories/sidebarActions.stories.tsx
> +const render = (arguments_: QuickActionsProperties) => (
Línea separar

2024-03-21 19:06 UTC, yurixander commented on src/utils/util.ts
> +    .find(member => member.userId !== room.myUserId)?.userId
Investiga si existe una manera de obtener un usuario directamente usando su ID, cómo si fuera un Map.get, eso es mucho mejor que buscar así

2024-03-21 19:56 UTC, criss8X commented on src/components/SidebarActions.tsx
> +}) => {
Concuerdo, es lo que estaba pensando, no había tomado esa decisión ya que estaba esperando a ver que tan complejo se ponía el componente como ahora.

2024-03-21 20:03 UTC, criss8X commented on src/hooks/matrix/useInvitationLink.ts
> +  }
Correcto, le puse try catch para gestionar el error que estaba dando a la hora de leer readText, tambien falla cuando el usuario no da permiso de clipboard.

2024-03-21 20:10 UTC, criss8X commented on src/hooks/matrix/useSidebarActions.ts
> +}
Entiendo, lo organizaré.

2024-03-22 18:54 UTC, yurixander requested changes

2024-03-22 18:54 UTC, yurixander commented on src/components/SidebarActions/useSidebarActions.ts
> +  }
useCallback

2024-03-22 18:54 UTC, yurixander commented on src/components/UserProfile.tsx
> +              isLarge ? "h-[17px] w-[17px]" : "h-[13px] w-[13px]",
size-[...]?

2024-03-22 18:54 UTC, yurixander commented on src/hooks/matrix/useUserSearch.ts
> +    }
Mejor nombre para esto: para que se usa el timerId? Describe su propósito en el nombre

2024-03-22 18:58 UTC, criss8X commented on src/components/UserProfile.tsx
> +              isLarge ? "h-[17px] w-[17px]" : "h-[13px] w-[13px]",
Cierto

2024-03-22 18:59 UTC, criss8X commented on src/hooks/matrix/useUserSearch.ts
> +    }
Ya hice useDebounced, se fue ahora en el push.

2024-03-22 18:59 UTC, criss8X commented on src/hooks/matrix/useUserSearch.ts
> +    }
Paso de llamarse timer, a handler

2024-03-22 19:01 UTC, yurixander submitted a review, later dismissed

2024-03-23 20:00 UTC, lazaroysr96 requested changes

2024-03-23 20:20 UTC, lazaroysr96 requested changes

2024-03-23 20:20 UTC, lazaroysr96 commented on src/components/Input.tsx
> +          className="w-full rounded-[10px] bg-neutral-50"
Prueba con rounded-lg 
![rrr](https://github.com/yurixander/mirage/assets/156694602/72c8228e-f9f7-473c-9fed-4296c3b2114d)

2024-03-23 20:20 UTC, lazaroysr96 commented on src/components/Input.tsx
> +        className="flex items-center rounded-[10px] border-[1px] border-solid border-neutral-300 bg-neutral-50"
borde**r-[1px]** es redundante ya que con border solo por defecto ya se obtiene 1px, acá también revisa el rounded-[10px] que puedes sustituir por rounded-lg, border-solid me parece que tampoco es requerido, por defecto border ya es solid
![bbb](https://github.com/yurixander/mirage/assets/156694602/fd4dc9bb-c474-48c3-8036-17c64095debe)

2024-03-23 20:20 UTC, lazaroysr96 commented on src/components/Input.tsx
>                  Icon={action.Icon}
tal ves icon en vez de Icon (que está iniciado con mayúscula)

2024-03-23 23:06 UTC, criss8X commented on src/components/ChatContainer.tsx
> +          <div className="flex max-h-[600px] max-w-[600px] flex-col gap-4 rounded-xl bg-slate-50 p-6 px-8 shadow-md">
Hecho

2024-03-23 23:07 UTC, criss8X commented on src/components/Input.tsx
> +          className="w-full rounded-[10px] bg-neutral-50"
Ese input esta asi, porque o era muy grande o muy chiquito, hay ocaciones en especifico que se usa el 10px, eso esta asi, hasta confirmar con el diseño.

2024-03-23 23:09 UTC, criss8X commented on src/components/Input.tsx
> +        className="flex items-center rounded-[10px] border-[1px] border-solid border-neutral-300 bg-neutral-50"
Hecho, lo del rounded-[10px] esta así hasta que  se confirme con el diseño original si se tomara 12, o 8.

2024-03-23 23:11 UTC, criss8X commented on src/components/SidebarActions/DirectMessageModal.tsx
> +            <div className="h-[1px] w-full bg-neutral-400" />
Perfecto, solucionado.

2024-03-23 23:11 UTC, criss8X commented on src/components/SidebarActions/DirectMessageModal.tsx
> +            <div className="h-[1px] w-full bg-neutral-400" />
Incluyendo el border-[1px] por border

2024-03-23 23:12 UTC, criss8X commented on src/components/Input.tsx
>                  Icon={action.Icon}
Ese Icon va con mayuscula para que encuadre con la etiqueta <Icon

2024-03-23 23:14 UTC, criss8X commented on src/components/Input.tsx
>                  Icon={action.Icon}
A vale si te refieres a action.Icon, bueno ahi si se puede poner en minuscula, lo acabo de hacer, pero en Icon= , no se pone ese icon con minuscula ya que debe encajar con etiqueta JSX

2024-03-24 04:30 UTC, yurixander requested changes

2024-03-24 04:30 UTC, yurixander commented on src/components/ChatContainer.tsx
> +        children={
Children prop es especial, se debería poner siempre dentro <Modal>...</Modal>

2024-03-24 04:30 UTC, yurixander commented on src/components/ChatContainer.tsx
> +                }}
sendImageMessage directamente en onClick

2024-03-24 04:30 UTC, yurixander commented on src/components/ChatContainer.tsx
> +                label={"Send Image"}
{}

2024-03-24 04:30 UTC, yurixander commented on src/components/Modal.tsx
> +            : "items-center justify-center"
Creo que esto se debería mover a una función junto con un switch

2024-03-24 04:30 UTC, yurixander commented on src/components/Navigation.tsx
> +        }
children, usar <Modal>...</Modal>

2024-03-24 04:30 UTC, yurixander commented on src/components/SidebarActions/DirectMessageModal.tsx
> +            <div className="h-px w-full bg-neutral-400" />
Esto que representa? Creo que sería bueno este caso para poner un comentario jsx

2024-03-24 04:30 UTC, yurixander commented on src/components/SidebarActions/DirectMessageModal.tsx
> +                }}
Usar función directa

2024-03-24 04:30 UTC, yurixander commented on src/components/SidebarActions/NotificationsModal.tsx
> +            {userComponent ?? ""} {event}
Porque ?? ""?

2024-03-24 04:30 UTC, yurixander commented on src/components/SidebarActions/NotificationsModal.tsx
> +              }}
Función poner directamente

2024-03-24 04:30 UTC, yurixander commented on src/components/SidebarActions/NotificationsModal.tsx
> +            />
Poner un todo para cosas de prueba

2024-03-24 04:30 UTC, yurixander commented on src/components/SidebarActions/SidebarActions.tsx
> +          }}
Poner todo

2024-03-24 04:30 UTC, yurixander commented on src/components/SidebarActions/SidebarActions.tsx
> +            throw new Error("Open extensions not implemented.")
Todo

2024-03-24 04:30 UTC, yurixander commented on src/components/SidebarActions/SidebarActions.tsx
> +          }}
Función directa

2024-03-24 17:14 UTC, criss8X commented on src/components/SidebarActions/NotificationsModal.tsx
> +              }}
Dime quito el comentario y lo pongo directo?

2024-03-24 17:16 UTC, criss8X commented on src/components/SidebarActions/NotificationsModal.tsx
> +            {userComponent ?? ""} {event}
Eso se me fue ahi, estaba probando porque no servian algunas clases de tailwindcss y era que al hacer una nueva carpeta dentro de components, habia que actualizar la configuracion de tailwindcss a ./src/components/**/*.{ts,tsx}

2024-03-24 17:18 UTC, criss8X commented on src/components/SidebarActions/NotificationsModal.tsx
> +            {userComponent ?? ""} {event}
Ah dices del operador ??, bueno porque el objetivo es que no se muestre

2024-03-24 17:20 UTC, criss8X commented on src/components/SidebarActions/NotificationsModal.tsx
> +            {userComponent ?? ""} {event}
Ya lo cambie por undefined

2024-03-24 17:26 UTC, criss8X commented on src/components/Avatar.tsx
> +        square
En realidad todos son Squared, pero bueno ahi te puse otra variablemas como prop

2024-03-24 17:28 UTC, criss8X commented on src/components/ChatContainer.tsx
> +                }}
Es asincrono, no se puede

2024-03-24 17:30 UTC, criss8X commented on src/components/SidebarActions/SidebarActions.tsx
> +          }}
Asincrono no se pone directo

2024-03-24 17:35 UTC, criss8X commented on src/components/Modal.tsx
> +            : "items-center justify-center"
Bueno, eso eso estaba en una funcion, pero me habias dicho que preferias usar ese modelo en lugar de funciones.

2024-03-24 17:39 UTC, criss8X commented on src/components/SidebarActions/DirectMessageModal.tsx
> +                }}
Es una funcion asincrona no puede ir directo

2024-03-24 17:40 UTC, criss8X commented on src/components/SidebarActions/DirectMessageModal.tsx
> +            <div className="h-px w-full bg-neutral-400" />
Se ve por el componente Typography que es el apartado de obtencion de el link de invitacion, pero bueno, ahi te dejaré un comentario.

2024-03-24 21:30 UTC, lazaroysr96 commented on src/components/Input.tsx
> +        className="flex items-center rounded-[10px] border border-neutral-300 bg-neutral-50"
Acá podríamos utilizar rounded-lg (8px) en ves de rounded-[10px]

2024-03-24 21:30 UTC, lazaroysr96 commented on src/components/Input.tsx
> +                Icon={action.icon}
icon

2024-03-24 21:30 UTC, lazaroysr96 commented on src/components/Modal.tsx
> +            : "items-center justify-center"
Si, me parece que en una función quedaría un poco mas legible y organizado, a la larga utilizar código tan compacto podría dar problemas para mantenerlo.

2024-03-24 21:30 UTC, lazaroysr96 commented on src/components/NotificationDot.tsx
>              "absolute right-0 top-0 h-[6px] w-[6px]",
acá podría simplificare un poco utilizando size en ves de h y w

2024-03-25 01:43 UTC, lazaroysr96 approved these changes

2024-03-26 16:35 UTC, yurixander requested changes

2024-03-26 16:35 UTC, yurixander commented on src/components/SidebarActions/SidebarActions.tsx
> +    </>
Se puede simplificar solo usando JavaScript

2024-03-27 14:04 UTC, yurixander submitted a review, later dismissed

2024-03-27 22:23 UTC, lazaroysr96 approved these changes

2024-03-28 05:14 UTC, yurixander approved these changes

2024-03-28 11:49 UTC, lazaroysr96 approved these changes

2024-03-28 13:36 UTC, merged