Creating RadioButton Component based on input type radio
yurixander/mirage pull request #23
Opened 2024-03-22 04:11 UTC by lazaroysr96

He desarrollado inicialmente este componente para RadioButton basado en input type radio, no quise tocar el código del componente originalmente creado para este propósito por Criss, al menos no por ahora, por lo tanto nombre estos como LRadioButton y LRadioGroup.

Acá unas capturas de como se ven
![i111](https://github.com/yurixander/mirage/assets/156694602/6c4ea7d6-16e1-4312-8741-fc35b470432a)
![i222](https://github.com/yurixander/mirage/assets/156694602/99d56663-27d0-4b51-93c8-c082d22a3fdd)

2024-03-22 04:23 UTC, yurixander requested changes

2024-03-22 04:23 UTC, yurixander commented on src/components/LRadioButton.tsx
> +    </>
No necesita <></> para un solo componente

2024-03-22 04:23 UTC, yurixander commented on src/components/LRadioButton.tsx
> +const LRadioButton: FC<LRadioButtonProps> = ({label, name, onClick}) => {
Línea vacía aquí separando esto

2024-03-22 04:23 UTC, yurixander commented on src/components/LRadioGroup.tsx
> +        />
Esto necesita el prop "key"

2024-03-22 04:23 UTC, yurixander commented on src/components/LRadioGroup.tsx
> +  return (
Separar estas líneas con una línea vacía

2024-03-22 04:23 UTC, yurixander commented on src/components/LRadioGroup.tsx
> +const LRadioGroup: FC<LRadioGroupProps> = ({
Porque llamarlo LRadioGroup y no RadioGroup? Cambiar nombre

2024-03-22 04:23 UTC, yurixander commented on src/stories/lRadioButton.stories.tsx
> +const render = (args: LRadioButtonProps) => <LRadioButton {...args} />
Separar con línea vacía

2024-03-22 04:23 UTC, yurixander commented on src/stories/lRadioGroup.stories.tsx
> +const render = (args: LRadioGroupProps) => <LRadioGroup {...args} />
Separar con línea vacía

2024-03-22 04:23 UTC, yurixander commented on src/components/LRadioButton.tsx
> +          id="purple"
Porque el id y valor es "purple"? El id debería provenir de los props igual que el valor

2024-03-22 04:23 UTC, yurixander commented on src/components/LRadioButton.tsx
> +const LRadioButton: FC<LRadioButtonProps> = ({label, name, onClick}) => {
Donde se gestiona la lógica de sobre si está seleccionado o no? Acepta un prop algo cómo "isSelected" para especificar si está seleccionado o no

2024-03-22 04:23 UTC, yurixander commented on src/components/LRadioButton.tsx
> +          className="size-4 cursor-pointer accent-purple-500"
Si el padre ya tiene cursor-pointer, el cursor pointer no es requerido aquí porque el padre ya lo cubre

2024-03-22 18:53 UTC, criss8X requested changes

2024-03-22 18:53 UTC, criss8X commented on src/components/LRadioButton.tsx
> +export default LRadioButton
Una línea de espacio vacía aquí, entre } y el `export`

2024-03-22 18:53 UTC, criss8X commented on src/components/LRadioGroup.tsx
> +const LRadioGroup: FC<LRadioGroupProps> = ({
Aquí faltan lineas de espacio vacías entre cada bloque de LRadioGroupProps, y LRadioGroupDirection y LRadioGroup.

Poner espacios vacíos entre las lineas: `12-13`  || `8-9`

2024-03-23 17:48 UTC, lazaroysr96 commented on src/components/LRadioButton.tsx
> +const LRadioButton: FC<LRadioButtonProps> = ({label, name, onClick}) => {
Para determinar si esta seleccionado o no se puede utilizar la propiedad checked nativa de los RadioButton, para el caso de determinar que grupo de RadioButtons, para que un grupo de RadioButton actúen como tal o se que al seleccionar uno de estos se deselecciona el antes seleccionado se utiliza la propiedad name, todos los RadioButtons con el mismo name actuaran como miembros de una misma pregunta, lo que cambia es el value, por otro lado esta onClick con lo que se puede implementar alguna lógica al clickear sobre estos.

2024-03-23 17:50 UTC, lazaroysr96 commented on src/components/LRadioButton.tsx
> +          className="size-4 cursor-pointer accent-purple-500"
En estos casos el RadioButton en particular no hace caso de la herencia, por lo que esta propiedad en particular si es requerida.

2024-03-23 18:04 UTC, lazaroysr96 commented on src/components/LRadioButton.tsx
> +          id="purple"
Acá al id le asignare el valor key ya que se supone que estos sean únicos, key supongo pueda ser perfectamente empleado como id, a valúe le asignaremos un valor por defecto pero también lo añadiremos a los props para que sea opcional darlo o no.

2024-03-23 23:19 UTC, yurixander requested changes

2024-03-23 23:19 UTC, yurixander commented on src/components/LRadioGroup.tsx
> +  isColum?: RadioGroupDirection
isColumn renombrar a direction, igual recuerda que se debería gestionar por el padre classnames en  vez de hacerlo por un prop

2024-03-23 23:19 UTC, yurixander commented on src/components/LRadioGroup.tsx
> +  isColum?: RadioGroupDirection
Es decir deshazte de esta propiedad y acepta "className?: string" en vez

2024-03-23 23:19 UTC, yurixander commented on src/components/LRadioGroup.tsx
> +          onClick={() => {}}
Pon un comentario TODO en lugares que no están completados / están parciales

2024-03-23 23:19 UTC, yurixander commented on src/components/LRadioButton.tsx
> +const RadioButton: FC<RadioButtonProps> = ({
Renombra el archivo también a que pegue con el nombre del componente

2024-03-24 02:14 UTC, lazaroysr96 commented on src/components/LRadioGroup.tsx
> +          onClick={() => {}}
Acá realmente va **props.onClick**, se me había escapado.

2024-03-24 02:17 UTC, lazaroysr96 commented on src/components/LRadioButton.tsx
> +const RadioButton: FC<RadioButtonProps> = ({
Existe un componente llamado RadioButton previamente creado, si lo renombro se estará reemplazará el anterior por este.

2024-03-24 04:18 UTC, yurixander commented on src/components/LRadioButton.tsx
> +const RadioButton: FC<RadioButtonProps> = ({
Si no se usa el previo, bórralo y deja este solamente

2024-03-24 13:37 UTC, yurixander requested changes
Solo unas cositas y está listo

2024-03-24 13:37 UTC, yurixander commented on src/components/RadioButton.tsx
> +      <span className="px-1.5">{label}</span>
Separar con línea blanca

2024-03-24 13:37 UTC, yurixander commented on src/stories/radioButton.stories.tsx
> +const render = (args: RadioButtonProps) => <RadioButton {...args} />
Separar con línea

2024-03-24 20:57 UTC, yurixander submitted a review, later dismissed

2024-03-25 12:38 UTC, criss8X approved these changes

2024-03-25 13:30 UTC, criss8X requested changes

2024-03-25 13:30 UTC, criss8X commented on src/components/RadioGroup.tsx
> +  return (
Agrega un TODO aquí para indicar que hay que gestionar la selección dentro de este radio group.

2024-03-25 13:30 UTC, criss8X commented on src/components/RadioGroup.tsx
> +  return (
// TODO: Handle here selection  radiobutton group by `name`, `value`, `checked`, `onChange`.

2024-03-25 13:30 UTC, criss8X commented on src/components/RadioGroup.tsx
> +  className: string
el className debe ser opcional, `className?: string`

2024-03-27 14:03 UTC, yurixander approved these changes

2024-03-27 14:23 UTC, criss8X approved these changes

2024-03-27 14:24 UTC, merged