feat: Implement notifications handling
yurixander/mirage pull request #25
Opened 2024-03-27 01:19 UTC by criss8X

2024-03-27 02:43 UTC, lazaroysr96 approved these changes

2024-03-29 07:09 UTC, yurixander submitted a review, later dismissed

2024-03-30 06:53 UTC, yurixander requested changes

2024-03-30 06:53 UTC, yurixander commented on src/components/SidebarActions/useNotifications.ts
> +    const notificationsTwo: NotificationProps[] = []
Mejor nombre: newNotifications

2024-03-30 06:53 UTC, yurixander commented on src/components/SidebarActions/useNotifications.ts
> +    body: "has invited for this room",
Esta gramática está rara

2024-03-30 06:53 UTC, yurixander commented on src/components/SidebarActions/useNotifications.ts
> +        }
Tira los errores si esto no debería pasar

2024-03-30 14:23 UTC, criss8X commented on src/components/SidebarActions/useNotifications.ts
> +    body: "has invited for this room",
El tema es que, se gestiona como un mensaje  por tanto el usuario tiene un nombre y un avatar, que puede ser usuario, o room, de todos modos, no he quitado este de draft, porque todavia estoy trabajando en el, ya que surgieron ciertas ideas con la conversación que tuvimos aquel dia.

2024-03-30 15:41 UTC, lazaroysr96 reviewed
Yo lo veo bastante bien, en el futuro podemos buscar como utilizar indexedDB para guardar datos en vez de localStorage

2024-03-31 20:10 UTC, yurixander requested changes

2024-03-31 20:10 UTC, yurixander commented on src/components/SidebarActions/NotificationsModal.tsx
> +            onAllMaskAsRead()
Mask o mark?

2024-03-31 20:10 UTC, yurixander commented on src/components/SidebarActions/NotificationsModal.tsx
> +            onAllMaskAsRead()
Creo que sería "onMarkAllAsRead"

2024-03-31 20:10 UTC, yurixander commented on src/components/SidebarActions/useNotifications.ts
> +  const {cachedNotifications, saveNotification, clearNotifications} =
Línea nueva

2024-03-31 20:10 UTC, yurixander commented on src/components/SidebarActions/useNotifications.ts
> +  const hasReason = event.getContent().reason
Quitar línea blanca

2024-03-31 20:56 UTC, lazaroysr96 approved these changes

2024-03-31 21:24 UTC, yurixander submitted a review, later dismissed

2024-03-31 22:16 UTC, yurixander requested changes

2024-03-31 22:16 UTC, yurixander commented on src/components/SidebarActions/useNotifications.ts
> +const powerLevelsEventNotificationTransformer = (
Mejor nombre más descriptivo, algo como getPowerLevelFromEvent

2024-03-31 22:16 UTC, yurixander commented on src/components/SidebarActions/useNotifications.ts
> +    body = `You has degraded you to ${powerLevel} at ${roomName}`
Gramática incorrecta, usa "demoted"

2024-03-31 22:16 UTC, yurixander commented on src/components/SidebarActions/useNotifications.ts
> +const mentionEventNotificationTransformer = (
Mejor nombre

2024-03-31 22:16 UTC, yurixander commented on src/components/SidebarActions/useNotifications.ts
> +const membersEventNotificationTransformer = (
Mejor nombre

2024-03-31 22:16 UTC, yurixander commented on src/components/SidebarActions/useNotifications.ts
> +      body: `your ban has been lifted in the ${roomName}`,
Porque este no empieza con mayúscula y los otros si ?

2024-03-31 22:16 UTC, yurixander commented on src/utils/util.ts
> +export enum AssertMessagesMoreUsed {
Cambiar nombre a "CommonAssertion", esto es una buena idea

2024-03-31 22:16 UTC, yurixander commented on src/utils/util.ts
> +  EventIdNotFound = "eventId should not be undefined",
No se trata de poner lo que no debería ser igual a, ya eso se sabe en la condición del assert, sino poner la **razon** por la cual ese assert debería siempre ser verdadero

2024-03-31 22:16 UTC, yurixander commented on src/utils/util.ts
> +  EventIdNotFound = "eventId should not be undefined",
Los assert proveen una manera de declarar y definir suposiciones que no pueden ser cubiertas por el sistema de tipos

2024-04-01 00:35 UTC, yurixander requested changes

2024-04-01 00:35 UTC, yurixander commented on .github/workflows/deploy-pages.yml
> +        publish_dir: ./src  # Replace with the directory where Vite build outputs files, if different
Quitar comentario, por cierto esto creo que seria algo como `dist/`

2024-04-01 00:35 UTC, yurixander commented on .github/workflows/deploy-pages.yml
> +      run: npm install
Yarn?

2024-04-01 11:14 UTC, lazaroysr96 commented on src/components/SidebarActions/useNotifications.ts
> +const powerLevelsEventNotificationTransformer = (
Si es recomendable que cualquier función que devuelva algo diga get y cualquiera que establezca algo diga set

2024-04-02 04:35 UTC, yurixander requested changes

2024-04-02 04:35 UTC, yurixander commented on src/components/SidebarActions/useCachedNotifications.ts
> +  }, [cachedNotifications, refreshContainsUnreadNotifications])
Explicar el proposito de este `useEffect` con un comentario

2024-04-02 04:35 UTC, yurixander commented on src/components/SidebarActions/useSidebarActions.ts
> +    containsUnreadNotifications,
Porque retornar el valor de un hook "X" (useNotificationsStateStore) desde otro "Y" (useSidebarActions), sin usar ese hook (X) dentro de hook Y? El que consuma el hook Y necesita ese valor? Si ese es el caso, haz que el consumidor llame al hook X directamente en vez de hacerlo pasar por otro hook

2024-04-02 21:37 UTC, yurixander requested changes

2024-04-02 21:37 UTC, yurixander commented on .github/workflows/deploy-pr-dev.yml
> +        publish_dir: ./dist
No creo que funcione tener dos, porque manda los cambios a la misma raíz... entonces una sobreescribe la otra. Eso de runs on es donde se ejecuta, no hacia dónde van los cambios

2024-04-02 21:37 UTC, yurixander commented on src/components/SidebarActions/SidebarActions.tsx
> +  const {notifications, markAsReadAllNotifications} = useNotifications()
Nuevo nombre: "markAllNotificationsAsRead"

2024-04-02 21:37 UTC, yurixander commented on src/components/SidebarActions/useCachedNotifications.ts
> +          )
Extrae esta condición a una variable

2024-04-02 21:37 UTC, yurixander commented on src/components/SidebarActions/useNotifications.ts
> +        },
Estar guardando estas funciones así no me convence, usualmente lleva a problemas inesperados, busca otra manera de gestionar esto sin guardar funciones en un array

2024-04-02 21:37 UTC, yurixander commented on src/components/SidebarActions/useNotifications.ts
> +        },
Preferiblemente la información que se guarde en un hook debería ser información estática es decir nada de funciones o elementos react

2024-04-02 21:37 UTC, yurixander commented on src/components/SidebarActions/useNotifications.ts
> +        },
Funciones dentro de un objeto

2024-04-02 21:37 UTC, yurixander commented on src/components/SidebarActions/useNotifications.ts
> +      return // Ignore past events when starting sync.
Pon el comentario arriba del return, siempre prefiere ese estilo: por arriba de algo, para consistencia

2024-04-02 21:37 UTC, yurixander commented on src/components/SidebarActions/useNotifications.ts
> +      return // If there is no room, the event may not be a mention event.
Comentario arriba

2024-04-02 21:37 UTC, yurixander commented on src/components/SidebarActions/useNotifications.ts
> +  assert(roomName !== undefined, "The room must exist")
Cuál es la razón por la cual user id nunca deberia faltar o el room no debería ser undefined? Pon las razones en el mensaje

2024-04-02 21:37 UTC, yurixander commented on src/components/SidebarActions/useNotifications.ts
> +  }
Porque? Que significa este caso/situacion? Explicar en un comentario breve

2024-04-02 21:37 UTC, yurixander commented on src/components/SidebarActions/useNotifications.ts
> +    return null
Tira un error "Not yet implemented" en vez de continuar ejecutando, o si te afecta el error y no te deja probarlo, dejar null por ahora está bien

2024-04-03 15:26 UTC, criss8X commented on src/components/SidebarActions/useNotifications.ts
> +        },
Voy a trabajar en una mejor implementación de Notificaciones, que gracias a este sistema no abra que hacerlo todo de nuevo, solo hacer ajustes. Con esa nueva implementación soluciono estas cosas.

2024-04-03 15:35 UTC, criss8X commented on src/components/SidebarActions/useNotifications.ts
> +        },
No entendi a que te refieres con eso, dentro del componente?

2024-04-05 06:37 UTC, yurixander requested changes

2024-04-05 06:37 UTC, yurixander commented on src/components/SidebarActions/useCachedNotifications.ts
> +  // }, [cachedNotifications, refreshContainsUnreadNotifications])
Codigo comentado quitar o poner TODO

2024-04-05 06:37 UTC, yurixander commented on src/components/SidebarActions/useNotifications.ts
> +        onRequestChanges,
Esto no me convence, aun estamos guardando funciones en un array 🤔

2024-04-05 06:37 UTC, yurixander commented on src/hooks/matrix/useGlobalEventListeners.ts
> +    useNotificationsStateStore()
linea blanca

2024-04-05 06:37 UTC, yurixander commented on src/hooks/matrix/useGlobalEventListeners.ts
> +    // The user ban was removed.
Pon esto arriba del if

2024-04-05 06:37 UTC, yurixander commented on src/utils/util.ts
> +  UserIdNotFound = "The client must be logged in.",
Siempre en las suposiciones usa 'should' en vez de 'must' por consistencia + explicito que es una suposicion

2024-04-05 06:37 UTC, yurixander commented on src/utils/util.ts
> +export enum CommonAssertion {
Solo usa esto si los mensajes si usan en mas de un lugar (2+), sino ponlos directamente en linea

2024-04-05 19:26 UTC, yurixander requested changes
Unas cositas de estilo de código y listo

2024-04-05 19:26 UTC, yurixander commented on src/components/SidebarActions/Notification.tsx
> +    deleteNotificationById(notificationId)
Quitar espacio extra

2024-04-05 19:26 UTC, yurixander commented on src/components/SidebarActions/Notification.tsx
> +    deleteNotificationById(notificationId)
Espacio extra

2024-04-05 19:26 UTC, yurixander commented on src/components/SidebarActions/NotificationsModal.tsx
>              clearActiveSidebarModal()
Espacio extra

2024-04-05 19:26 UTC, yurixander commented on src/components/SidebarActions/NotificationsModal.tsx
> +            {...notification}
El prop "key" ya está incluido aquí? Generalmente prefiero que pongás el key prop directamente aquí en vez de hacerlo parte de un objeto

2024-04-05 19:26 UTC, yurixander commented on src/hooks/matrix/useGlobalEventListeners.ts
> +      // If there is no room, the event may not be a mention event.
Comentarios arriba del if

2024-04-05 19:26 UTC, yurixander commented on src/hooks/matrix/useGlobalEventListeners.ts
> +    // If the body is null then the power levels event did not occur or was not processed by the room.
Comentario arriba del if

2024-04-05 19:26 UTC, yurixander commented on src/hooks/matrix/useGlobalEventListeners.ts
> +  if (member?.membership !== "ban" && prevContent.membership === "ban") {
Quitar línea blanca en el medio

2024-04-05 19:26 UTC, yurixander commented on src/utils/util.ts
>      const member = joinedMembers[adminId]
Agregar línea separadora

2024-04-06 06:11 UTC, yurixander requested changes

2024-04-06 06:11 UTC, yurixander commented on src/components/SidebarActions/NotificationsModal.tsx
> +              {...notification}
key? Una pregunta, cuando haces cambios y pruebas la app y eso, estas prestando atencion a la consola? El React te deberia estar dando warning o error por omitir el key aqui.

2024-04-06 06:11 UTC, yurixander commented on src/containers/ChatContainer/ChatContainer.tsx
> +              void sendTextMessage(query)
Aprovecha y cambiale en nombre a la variable `query` porque query es mas que ver con busqueda, aqui puedes ponerle un nombre como `message` o `messageText` que es mas apropiado

2024-04-06 06:11 UTC, yurixander commented on src/hooks/matrix/useActiveRoom.ts
> +        msgtype: MsgType.Text,
MsgType -> MessageType

2024-04-06 06:11 UTC, yurixander commented on src/hooks/matrix/useGlobalEventListeners.ts
> +    body = `you has demoted you to ${powerLevel} at ${roomName}`
you has demoted you? Esta mal esto

2024-04-06 06:11 UTC, yurixander commented on src/utils/notifications.ts
> +  const isExist = savedNotifications.some(
isExist -> exists

2024-04-06 06:11 UTC, yurixander commented on src/utils/util.ts
> +export function checkIsDirectRoom(
checkIsDirectRoom -> isDirectRoom

2024-04-06 13:45 UTC, criss8X commented on src/hooks/matrix/useActiveRoom.ts
> +        msgtype: MsgType.Text,
Eso es de Matrix no es mio

2024-04-07 03:42 UTC, yurixander approved these changes

2024-04-07 04:24 UTC, lazaroysr96 commented on src/components/SidebarActions/NotificationsModal.tsx
>              {...notification}
en java se usa algo como por ejemplo:
```
private void setGradient(View v,int...colors){
GradientDrawable gd = new GradientDrawable();
if(colors.length==1){
gd.setColor(colors[0]);
}else{
gd.setColors(colors);
}
v.setBackground(gd);
}
```
o sea se usa para pasar un numero indeterminado de valores, esa sentencia de 3 puntitos ahí es la misma??

2024-04-07 04:27 UTC, lazaroysr96 approved these changes

2024-04-07 23:15 UTC, merged