feat: Implement dark mode in ChatHeader
yurixander/mirage pull request #252
Opened 2024-11-15 00:51 UTC by lazaroysr96

## Implementación del modo Oscuro en el ChatHeader

### Progreso:

 - [ ] Agregar variante dark/oscuro para los componentes nuevos creados.

2024-11-18 21:54 UTC, yurixander requested changes

2024-11-18 21:54 UTC, yurixander commented on src/components/SmartActionBar.tsx
> +  document.querySelectorAll("html")[0].className = theme
Esto deberia estar dentro de un useEffect

2024-11-18 21:54 UTC, yurixander commented on src/components/SmartActionBar.tsx
> +  document.querySelectorAll("html")[0].className = theme
O useLayoutEffect o algo asi, pero nunca fuera en el codigo de la funcion del componente

2024-11-18 21:54 UTC, yurixander commented on src/hooks/util/useTheme.ts
> +  }
localStorage deberia solo usarse dentro de useEffects

2024-11-18 21:54 UTC, yurixander commented on src/hooks/util/useTheme.ts
> +  document.querySelectorAll("html")[0].className = isDarkTheme ? "dark" : ""
Deberia estar dentro de useEffect

2024-11-18 21:54 UTC, yurixander commented on src/hooks/util/useTheme.ts
> +  }
Ponlo dentro de un useCallback

2024-11-22 11:58 UTC, yurixander requested changes

2024-11-22 11:58 UTC, yurixander commented on src/hooks/util/useTheme.ts
> +  const salvedTheme = localStorage.getItem("darkMode")
```suggestion
  const savedTheme = localStorage.getItem("darkMode")
```

2024-11-22 11:58 UTC, yurixander commented on src/hooks/util/useTheme.ts
> +  }
Pon esto en un useCallback

2024-11-22 11:58 UTC, yurixander commented on src/hooks/util/useTheme.ts
> +  }
Y renombralo a algo como "toggleTheme"

2024-11-22 13:41 UTC, criss8X commented on src/hooks/util/useTheme.ts
> +  const [isDarkTheme, setIsDarkTheme] = useState(isDarkMode)
para la gestion del local storage hay un hook llamado useLocalStorage que sirve para manejar el estado ya lo hace casi todo

2024-11-24 02:08 UTC, yurixander approved these changes

2024-11-24 13:39 UTC, criss8X approved these changes

2024-11-24 13:39 UTC, merged