Lazaroysr96/skeleton loading
yurixander/mirage pull request #29
Opened 2024-03-31 21:25 UTC by lazaroysr96

Ya pueden revisar el componente ChatContainerLoader, quedo a la espera de sus sugerencias, les dejo una captura de como quedó aquí, por ahora es estático, o sea siempre se verá así.
![2024-03-30_223524](https://github.com/yurixander/mirage/assets/156694602/d50b37d9-d32a-4a00-9e07-250ebf20444a)

2024-03-31 21:26 UTC, yurixander requested changes

2024-03-31 21:26 UTC, yurixander commented on src/components/ChatContainerLoader.tsx
> +          "relative  overflow-hidden rounded-full bg-neutral-300",
Espacio extra

2024-03-31 21:33 UTC, yurixander submitted a review, later dismissed

2024-04-01 16:42 UTC, criss8X requested changes

2024-04-01 16:42 UTC, criss8X commented on src/components/ChatContainerLoader.tsx
> +        <div className="inline-flex flex-col gap-1">
Espacio entre Skeleton y el div

2024-04-01 16:42 UTC, criss8X commented on src/components/ChatContainerLoader.tsx
> +          <SkeletonLine />
Otro espacio entre estos 2 skeletons line

2024-04-01 16:42 UTC, criss8X commented on src/components/ChatContainerLoader.tsx
> +        <div className="inline-flex flex-col gap-1">
Otro espacio entre el SkeletonCircle y el div

2024-04-01 16:42 UTC, criss8X commented on src/components/ChatContainerLoader.tsx
> +          <div className="flex flex-row gap-1.5">
Otro espacio mas aca

2024-04-01 16:42 UTC, criss8X commented on src/components/ChatContainerLoader.tsx
> +          </div>
espacio entre estos 2 divs, los SkeletonLine que estan juntos estan bien, solo es espacio entre los divs

2024-04-01 16:42 UTC, criss8X commented on src/components/ChatContainerLoader.tsx
> +        <div className="inline-flex flex-col gap-1">
Otro espacio más aquí, entre SkeletonCircle y el div

2024-04-01 16:42 UTC, criss8X commented on src/components/ChatContainerLoader.tsx
> +        <div className="inline-flex flex-col gap-1">
Otro espacio entre el Skeleton y el div

2024-04-01 16:42 UTC, criss8X commented on src/components/ChatContainerLoader.tsx
> +          <div className="flex flex-row gap-1.5">
Otro espacio aca entre el skeleton y el div tambien

2024-04-01 16:42 UTC, criss8X commented on src/components/ChatContainerLoader.tsx
> +          <div className="flex flex-row gap-1.5">
Otro espacio entre los divs

2024-04-01 16:42 UTC, criss8X commented on src/components/ChatContainerLoader.tsx
> +          <div className="flex flex-row gap-1.5">
Otro aca

2024-04-01 16:42 UTC, criss8X commented on src/components/ChatContainerLoader.tsx
> +}
Aquí, creo que es mejor comprobar si `className `existe y si no tirar el `h-3` `w-80` directo en el `twMerge`, que ponerlo directo arriba, no se que crea @yurixander sobre ello.

2024-04-01 16:42 UTC, criss8X commented on src/stories/chatContainerLoader.stories.tsx
> +}
espacio aqui

2024-04-06 13:03 UTC, lazaroysr96 commented on src/components/ChatContainerLoader.tsx
> +          <SkeletonLine />
Cada grupo de Skeleton line forman parte de un bloque de lineas, para entender que pertenecen al mismo bloque es mejor que estén juntos.

2024-04-06 13:31 UTC, lazaroysr96 commented on src/components/ChatContainerLoader.tsx
> +}
algo así:
`className ?? "h-3 w-80"`

2024-04-07 07:25 UTC, yurixander approved these changes

2024-04-07 23:16 UTC, criss8X commented on src/components/ChatContainerLoader.tsx
> +}
> algo así: `className ?? "h-3 w-80"`

Si, eso que mencionaste esta bien

2024-04-08 20:57 UTC, yurixander commented
@criss8X

2024-04-08 21:01 UTC, criss8X approved these changes

2024-04-08 21:01 UTC, merged