feat: Update `ChatContainer` for state handling
yurixander/mirage pull request #31
Opened 2024-04-09 20:59 UTC by criss8X

### Actualizando y mejorando el ChatContainer

* Usè el componente `WelcomeChatContainer` en el caso de que no hay ninguna room seleccionada.
* Implementé `MessagesState` enum para gestionar cuando se estan cargando mensajes y cuando no.
* Usè el componente `ChatContainerLoader` para dar la sensaciòn de cargando cuando se cargan mensajes de una room.

2024-04-13 17:04 UTC, lazaroysr96 requested changes

2024-04-13 17:04 UTC, lazaroysr96 commented on src/containers/ChatContainer/ChatInput.tsx
> +      textarea.style.height = `${textarea.scrollHeight}px`
Aquí tal vez se podría implementar tailwind de algún modo.

2024-04-13 17:06 UTC, criss8X commented on src/containers/ChatContainer/ChatInput.tsx
> +      textarea.style.height = `${textarea.scrollHeight}px`
La verdad si, sacaron una nueva propiedad de text area que lo que hace es que eso lo hace automatico pero nosotros haremos nuestro propio Input asique eso no sera tan necesario,  no es necesario usar tailwindcss ahi

2024-04-13 17:06 UTC, criss8X commented on src/containers/ChatContainer/ChatInput.tsx
> +      textarea.style.height = `${textarea.scrollHeight}px`
Cuando leas esto me dices para marcar como resuelto

2024-04-13 17:07 UTC, criss8X commented on src/containers/DevPreview.tsx
Que cosa ?

2024-04-13 17:17 UTC, lazaroysr96 requested changes

2024-04-13 17:17 UTC, lazaroysr96 commented on src/containers/DevPreview.tsx
> +      />
Me refiero a lo que se está mostrando acá en el DevPreview, suponiendo que sea código de prueba y no necesites que se valla a la raíz dev.

2024-04-13 17:18 UTC, criss8X commented on src/containers/DevPreview.tsx
> +      />
Ahhhh, vale vale si voy a quitar eso

2024-04-13 17:19 UTC, lazaroysr96 commented on src/containers/DevPreview.tsx
El contenido de DevPreview, de no ser que se requiera su fusión a la raíz dev.

2024-04-13 21:18 UTC, yurixander requested changes

2024-04-13 21:18 UTC, yurixander commented on src/components/ImageZoom.tsx
> +const ImageZoom: React.FC<ImageZoomProps> = ({className, src}) => {
Hay lugares que usan solo `FC` y otros que usan `React.FC` otra cosa seria si se usa `React.` en un lado, entonces todo lado deberia hacerlo. Tenemos que elegir, y creo que deberiamos quedarnos con `FC` solamente sino tenemos que meterle `React.` a todo

2024-04-13 21:18 UTC, yurixander commented on src/components/ImageZoom.tsx
> +    const delta = event.deltaY * -0.01
Separar

2024-04-13 21:18 UTC, yurixander commented on src/containers/ChatContainer/ChatInput.tsx
> +      textarea.style.height = `${textarea.scrollHeight}px`
En este caso no se puede usar tailwind porque la propiedad tiene que hacerce usando JS, asi que no hay de otra, asi esta bien en este caso

2024-04-13 21:18 UTC, yurixander commented on src/hooks/matrix/useActiveRoom.ts
> +        setMessagesState(MessagesState.Loaded)
Y esto separado

2024-04-15 06:04 UTC, yurixander requested changes

2024-04-15 06:04 UTC, yurixander commented on src/components/Navigation.tsx
> +              <ServerListItem {...server} />
Key?

2024-04-15 06:04 UTC, yurixander commented on src/hooks/matrix/useActiveRoom.ts
> +}
Usa un boleano isLoading

2024-04-15 14:48 UTC, criss8X commented on src/hooks/matrix/useActiveRoom.ts
> +}
isLoading? si es un esado seria `Loading` no ? o pongo isLoading asi tal cual?

2024-04-17 08:51 UTC, yurixander approved these changes

2024-04-17 23:19 UTC, lazaroysr96 approved these changes

2024-04-18 03:56 UTC, merged