feat: Updating Button and Dropdown components
yurixander/mirage pull request #32
Opened 2024-04-14 23:42 UTC by lazaroysr96

### Actualizando los componentes Button y Dropdown a diseño en Figma

2024-04-18 04:07 UTC, criss8X commented
La rama tiene conflictos bro

2024-04-21 13:26 UTC, criss8X requested changes

2024-04-21 13:26 UTC, criss8X commented on src/components/Button.tsx
> +            : ""
Si cambiaste la variante del botón secundaria de `purple` a `green` debes hacerlo con todas las variantes de el botón, o agregar un nuevo color, llamado green en este caso.

Veo que en el borde pusiste color directo, si no encontraste un color de los de tailwindcss y debes usar un color en especifico, debes establecerlo en tailwindcss.config para un mejor uso con los temas claro y oscuro cuando se configure.

2024-04-21 13:26 UTC, criss8X commented on src/components/Button.tsx
> +      <div className="size-4 animate-rotation rounded-full border-2 border-white border-t-[rgba(255,255,255,0.5)]" />
Aqui tienes un `rgba` puesto directo, debes ponerlo en tailwindcss.config

2024-04-21 13:26 UTC, criss8X commented on src/components/CreateRoom.tsx
> +        />
Espacio en blanco entre estos 2 botones

2024-04-21 13:26 UTC, criss8X commented on src/components/Dropdown.tsx
> +  const [visivility, setVisivility] = useState("hidden")
Para manejar estados de visibilidad u otra cosa, es mas legible y mas comodo usar enums, en lugar de usar un useState("hidden)

2024-04-21 13:26 UTC, criss8X commented on src/components/Dropdown.tsx
> +  const [visivility, setVisivility] = useState("hidden")
De hecho esto es un mal uso de clases de tailwindcss, tailwindcss usa string de forma fija, no se suscribe a un estado, no pudes guardar clases de tailwindcss en un estado asi, en lugar de eso usa un enum algo como `DropdownOptionVisibility` y ponle el estado de hidden y su otro estado y luego en el setVisibility le pasas ese estado y lo gestionas en el twMerge de abajo

2024-04-21 13:26 UTC, criss8X commented on src/components/Dropdown.tsx
> +          visivility
Aqui vendria algo como,

 visibility === DropdownOptionVisibility.Hidden ? "clase de tailwindcss" : "la otra clase de tailwindcss"

2024-04-21 13:26 UTC, criss8X commented on src/components/Dropdown.tsx
> +            }}
Probablemente me equivoco pero quizas exista una mejor forma de gestionar el estado de dropdown option, de forma interna quizas, me da mala espina tantos `set` de estados dentro de un onClick y al final otro on click mas.

2024-04-21 13:26 UTC, criss8X commented on src/components/Dropdown.tsx
> +}
Código extra que puedes borrar

2024-04-21 17:50 UTC, lazaroysr96 commented on src/components/Dropdown.tsx
> +  const [visivility, setVisivility] = useState("hidden")
Me parece bien tu recomendación pero creo que aquí quedaría mejor manejar el estado de visibilidad por un boolean, o sea quedaría esto:
`const [isDropdownOptionVisibility, setIsDropdownOptionVisibility] =
    useState(false)`

luego la función del button sería:
`setIsDropdownOptionVisibility(!isDropdownOptionVisibility)`

y para finalizar en twMerge
`isDropdownOptionVisibility ? "inline-block" : "hidden"`

2024-04-21 17:54 UTC, lazaroysr96 commented on src/components/Dropdown.tsx
> +}
Este componente se utiliza para mostrar el icono del Dropdown y poder cambiarlo dinamicamente en dependencia de la opción seleccionada.

2024-04-21 18:15 UTC, lazaroysr96 commented on src/components/Dropdown.tsx
> +            }}
Ese último `option.onClick()` activa la función onClick enviada desde afuera, los `set` actualizan el estado, quizás pudiera hacerse una función aparte llamada actualizar estado o updateState pero igual habría que llamarla desde el evento `onClick` de la opción seleccionada

2024-04-21 23:26 UTC, lazaroysr96 commented on src/components/Button.tsx
> +            : ""
El borde directo se debe a que al parecer el color de los bordes en el diseño que hay en Figma al momento de haber echo este componente no estaba dado en valores de TailWind, acá optaré por buscar un color en tailwind que se le acerque.

El Color negro lo deje para que no se rompan otros componentes, básicamente está ahí por una cuestión de compatibilidad, en realidad no está haciendo nada, aunque cero que implementare una lógica para poder cambiar el color y añadir otros colores.

2024-04-22 10:32 UTC, criss8X commented on src/components/Dropdown.tsx
> +  const [visivility, setVisivility] = useState("hidden")
Si, es buena opcion

2024-04-23 11:03 UTC, yurixander requested changes

2024-04-23 11:03 UTC, yurixander commented on src/components/Dropdown.tsx
> +          />
`key` prop

2024-04-25 00:02 UTC, criss8X requested changes
Necesitas reparar los conflictos con la rama, te subi un tutorial de 10 minutos, 30Mb al grupo

2024-04-25 00:02 UTC, criss8X commented on src/components/Dropdown.tsx
> +  const [isDropdownOptionVisibility, setIsDropdownOptionVisibility] =
mejor Visibility es algo muy general, algo como Visible es mejor

2024-04-25 00:02 UTC, criss8X commented on src/components/Dropdown.tsx
> +  const [label, setLabel] = useState(options[0].label)
Espacio ya que ese useState tiene 2 lineas

2024-05-02 23:27 UTC, yurixander approved these changes

2024-05-02 23:48 UTC, criss8X requested changes
Siguen habiendo problemas, Solucionar:

![image](https://github.com/yurixander/mirage/assets/100869331/cd60d739-db30-4d18-93ef-11017320dd11)

![image](https://github.com/yurixander/mirage/assets/100869331/45d89acd-fd02-4392-ab34-539b9542e059)

Probablemente este ultimo sea problema de tailwindcss

2024-05-03 14:02 UTC, merged