feat: Implement new `hooks`
yurixander/mirage pull request #35
Opened 2024-04-21 18:05 UTC by criss8X

## Aqui estaré implementando nuevos hooks, y organizando nuevas utilidades.

## En progreso:

- [ ] Implementando hook useLocalStorage

* Solucione el problema que surgio al actualizar matrix sdk js sobre manejo de undefined en la obtencion de miembros de una room.

2024-04-29 16:07 UTC, lazaroysr96 submitted a review, later dismissed

2024-05-02 23:25 UTC, yurixander requested changes

2024-05-02 23:25 UTC, yurixander commented on src/utils/members.ts
> +    ?.getContent().users as string[]
Porque usar as? Tratar siempre de evitarlo, al menos que sea necesario y justificado

2024-05-03 13:37 UTC, yurixander approved these changes

2024-05-05 03:55 UTC, lazaroysr96 approved these changes

2024-05-05 11:56 UTC, merged