feat: Create Component Slider
yurixander/mirage pull request #38
Opened 2024-05-08 02:37 UTC by lazaroysr96

### Creación del Componente Slider

![imagen](https://github.com/yurixander/mirage/assets/156694602/f6b73085-6417-46fa-836c-d69b39509954)

Completé la creación del componente Slider en sus dos variantes, este está desarrollado a partir de la base de un `input type range`, para lograr el efecto de mostrar una parte vasía y la otra llena por así decirlo, tecnicamente el input es invisible, solo está ahí funcionando como controlador, la parte visible está echa a partir de divs.

![imagen](https://github.com/yurixander/mirage/assets/156694602/d421f296-ef5c-4f5b-91a1-a530de5f3202)

La variante Step solo debe ser usada para valores de 0 a 100 iterando entre rangos de 20 para un total de 5 niveles de volumen, siempre debe usarse con valores equivalentes, o sea si el máximo es 50 entonces el valor de step debe ser 10, de lo contrario sucederá esto:
![imagen](https://github.com/yurixander/mirage/assets/156694602/66cbc9d7-7028-4930-9dd1-ca5881f85e17)

2024-05-09 17:38 UTC, criss8X requested changes
Quedan cosas todavía pero marcha bien.

2024-05-09 17:38 UTC, criss8X commented on src/components/Slider.tsx
> +  const handleOnInput = (event: React.ChangeEvent<HTMLInputElement>) => {
codigo multiliniea separalo con el de arriba, osea espacio entre linea 27 y 28

2024-05-09 17:38 UTC, criss8X commented on src/components/Slider.tsx
> +      </div>
espacio aqui entre div, y el isVatriantBasic

2024-05-09 17:38 UTC, criss8X commented on src/components/Slider.tsx
> +      <input
otro espacio aqui

2024-05-09 17:38 UTC, criss8X commented on src/components/Slider.tsx
> +}
otro espacio mas

2024-05-09 17:38 UTC, criss8X commented on src/components/Slider.tsx
> +      </div>
espacio entre 81 y 82

2024-05-09 17:38 UTC, criss8X commented on src/components/Slider.tsx
> +        className="relative top-[-16px] h-3 w-60 cursor-pointer appearance-none rounded-full bg-transparent p-0 slider"
Aqui en lugar de usar `top-[-16px]` -> usa `-top-4`

2024-05-09 17:38 UTC, criss8X commented on src/components/Slider.tsx
> +        max={max ?? "100"}
usa numero en lugar de string

2024-05-09 17:38 UTC, criss8X commented on src/components/Slider.tsx
> +        step={step ?? "1"}
Igual que en min, y step, prefiere usar numero en lugar de string

2024-05-09 17:38 UTC, criss8X commented on src/components/Slider.tsx
> +      <Step /> <Step /> <Step /> <Step /> <Step />
Porque los step los tiene puesto a mano?, ahi debe haber un mapeo que por la X cantidad de step que se le ponga sea el equivalente

2024-05-11 21:34 UTC, yurixander requested changes

2024-05-11 21:34 UTC, yurixander commented on src/components/Slider.tsx
> +  const [progress, setProgress] = useState(initialValue)
Porque el progreso es un string y no un numero?

2024-05-14 02:12 UTC, yurixander submitted a review, later dismissed

2024-05-14 03:11 UTC, lazaroysr96 commented on src/components/Slider.tsx
> +      <Step /> <Step /> <Step /> <Step /> <Step />
La variante step está pensada para iterar entre 5 niveles, aquí simplemente seguí el diseño en FIGMA.

2024-05-14 03:18 UTC, lazaroysr96 commented on src/components/Slider.tsx
> +  const [progress, setProgress] = useState(initialValue)
Es necesario que sea un string debido a que estoy utilizando twMerge para aumentar la barra de progreso a través de x progress + %, twMerge solo trabaja con string.

2024-05-14 14:54 UTC, yurixander commented on src/components/Slider.tsx
> +  const [progress, setProgress] = useState(initialValue)
Usa `style` solo para el caso del width, igual el tw-merge / valores de tailwind nunca se deberian crear dynamicamente ejemplo `"w-" + miVariable`, siempre deben ser estaticos: `w-4`. En este caso especifico, usa algo como `style={{ width: `${miVariable}%` }}`

2024-05-15 12:24 UTC, criss8X commented on src/components/Slider.tsx
> +      <Step /> <Step /> <Step /> <Step /> <Step />
El objetivo es que sea un componente reutilizable y generico, debe tener la posibilidad de ponerle los niveles a placer

2024-05-15 16:38 UTC, yurixander commented on src/components/Slider.tsx
> +      <Step /> <Step /> <Step /> <Step /> <Step />
El diseno en Figma es mayormente para referencia de como se ve / estilo, la funcionalidad puede variar @lazaroysr96

2024-05-19 21:55 UTC, criss8X requested changes

2024-05-19 21:55 UTC, criss8X commented on src/components/Button.tsx
> -export default Button
Porque se borro esto?

2024-05-19 22:24 UTC, criss8X commented on src/components/Slider.tsx
> +  initialValue?: string
initialValue debe ser un numero

2024-05-19 22:25 UTC, criss8X commented on src/components/Slider.tsx
> +  Icon: IconType
haslo mas generico, no le pongas ni titulo ni icono

2024-05-19 22:27 UTC, criss8X commented on src/components/Slider.tsx
> +  max?: number
Tanto el minimo como el maximo deben ser props obligadas y no opcionales, por cierto considera usar una Tupla de number-number de forma tal que sea un Range.

2024-05-19 22:28 UTC, criss8X commented on src/components/Slider.tsx
> +  onInput: (value: string) => void
onInput es un nombre complicado para comprender que hace.

2024-05-19 22:29 UTC, criss8X commented on src/components/Slider.tsx
> +export default Slider
Export default siempre al final para consistencia

2024-05-19 22:30 UTC, criss8X commented on src/components/Slider.tsx
> +  progress: string
si solo tiene una sola prop, mejor hacer: FC<{progress: string}>

2024-05-19 22:32 UTC, criss8X commented on src/components/Slider.tsx
> +}
El componente Step no es del todo reutilizable, en este caso mejor ponlo sin componente, pero en lugar de repetirlo hacer un map con la cantidad de steps que se ponga en las props

2024-05-19 22:32 UTC, criss8X commented on src/components/Slider.tsx
> +    onInput(value)
No me queda claro que hace el onInput

2024-05-19 22:48 UTC, criss8X requested changes
Checkea este codigo fue lo que te comente por whatsapp

```ts
import {useState, type FC} from "react"
import React from "react"

const DevelopmentPreview: FC = () => {
  const [value, setValue] = useState(50)

  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setValue(Number(event.target.value))
  }

  return (
    <div className="container mx-auto my-8">
      <div className="flex flex-col items-center">
        <input
          type="range"
          min={0}
          max={100}
          step={25}
          value={value}
          onChange={handleChange}
          className="w-full"
        />
        <div className="mt-4 text-xl">{`Valor: ${value}`}</div>
      </div>
      <div className="mt-8 flex justify-center">
        <div
          className="flex h-64 w-full max-w-lg items-center justify-center bg-blue-500 text-2xl text-white transition-transform"
          style={{transform: `scale(${1 + value / 100})`}}>
          Slider Content
        </div>
      </div>
    </div>
  )
}

export default DevelopmentPreview
```

2024-05-20 04:41 UTC, lazaroysr96 commented on src/components/Button.tsx
> -export default Button
Esta linea la puse mas arriba, particularmente al finalizar el código propio del Button.

2024-05-20 04:44 UTC, lazaroysr96 commented on src/components/Slider.tsx
> +    onInput(value)
Es lo mismo que onChange

2024-05-20 04:45 UTC, lazaroysr96 commented on src/components/Slider.tsx
> +  progress: string
A mi también me parece mas cómodo así, pero pensé que no era una buena practica hacer eso.

2024-05-22 22:04 UTC, criss8X commented on src/components/Slider.tsx
> +    onInput(value)
Un nombre más explicito

2024-05-22 22:05 UTC, criss8X commented on src/components/Slider.tsx
> +  progress: string
Si tienes pocas props puedes hacerlo

2024-05-22 22:08 UTC, criss8X requested changes

2024-05-22 22:08 UTC, criss8X commented on src/components/Button.tsx
> +}
Espacio entre 71 y 72

2024-05-23 02:36 UTC, lazaroysr96 commented on src/components/Slider.tsx
> +}
Técnicamente el componente step aquí está siendo solo decorativo, opcionalmente podríamos asignarle un evento onclick a este para que haga algo cuando lo toques, pero esencialmente las dos variantes son lo mismo, solo cambia el estilo.

2024-05-23 03:26 UTC, criss8X requested changes

2024-05-23 03:26 UTC, criss8X commented on src/components/Button.tsx
> +type LoadingProps = {
el nombre textLoading es redundante, se sabe que es un texto de loading, mejor usar simplemente `text`

2024-05-23 03:26 UTC, criss8X commented on src/components/Slider.tsx
> +        <StepProgressBar steps={(max - min) / (step ?? 1)} />
En lugar de verificar si es variante basica o no, puedes hacer que si contiene steps entonces se muestra el StepProgressBar, tratar de si se puede hacer una gestion dentro sin tener que solicitar algo mas por prop hacerlo, en este caso `step === undefined ? <BasicProgressBar /> : <StepProgressBar />`

2024-05-23 03:26 UTC, criss8X commented on src/components/Slider.tsx
> +      <Step />
porque tiene un Step solo aqui?

2024-05-23 03:26 UTC, criss8X commented on src/components/Slider.tsx
> +      ))}
Si opt no se usa poner `_`

2024-05-23 03:26 UTC, criss8X commented on src/components/Slider.tsx
> +      <div>
94 - 95 lleva espacio

2024-05-23 03:26 UTC, criss8X commented on src/components/Slider.tsx
> +  }
Con Array.from se puede hacer de una mejor forma, aunque eso que hiciste esta correcto

2024-05-23 04:44 UTC, lazaroysr96 commented on src/components/Slider.tsx
> +        <StepProgressBar steps={(max - min) / (step ?? 1)} />
Es que esta característica podría usarse con el slider normal, habría que pensarlo bien.

2024-05-23 04:54 UTC, lazaroysr96 commented on src/components/Slider.tsx
> +      <Step />
sip, tenía un objetivo inicial ahí, pero veo que en realidad no lo necesito.

2024-05-23 04:55 UTC, lazaroysr96 commented on src/components/Slider.tsx
> +      ))}
No me sabia esa, gracias.

2024-05-27 13:09 UTC, criss8X requested changes
Queda que sobreescribas los cambios del boton cuando se haga merge

2024-05-27 13:09 UTC, criss8X commented on src/components/Slider.tsx
> +  const [internalValue, setInternalValue] = useState(initialValue)
En lugar de usar doble logica, progreso y internalValue, deja internalValue y has el calculo dentro del componente que necesita hacer el calculo

2024-05-27 13:09 UTC, criss8X commented on src/components/Slider.tsx
> +  }
Puede ser mejorado con un Array.from

2024-05-27 13:09 UTC, criss8X commented on tailwind.config.ts
> +      }
Bro que hiciste aqui, porque añadiste esto?

2024-05-27 13:09 UTC, criss8X commented on tailwind.config.ts
> +        backgroundButtonDisabled: "#22C55E",
borrar esto, el borderLoading se debe poder hacer sin eso

2024-05-28 03:50 UTC, lazaroysr96 commented on tailwind.config.ts
> +      }
Esto es para el Thumb del slider, se encarga de eliminar la apariencia por defecto de este y añadir la apariencia que quiero darle.

2024-05-28 03:50 UTC, lazaroysr96 commented on tailwind.config.ts
> +      }
Esto ahora lo pase para tailwind.css

2024-05-28 04:19 UTC, lazaroysr96 commented on src/components/Slider.tsx
> +        style={{width: progress + "%"}}
En este caso una concatenación me parece mas simple que una plantilla literaria, técnicamente lo que ocurre es que ahora se considera mas moderno utilizar template literals, o sea un estándar que vino con ES6, (Personalmente yo lo veo como una forma de complicar la legibilidad del código, con una concatenación es mucho mas evidente lo que se está haciendo que con eso, no obstante yo no escribo los estándares, así que en este caso aplicaré Template Literals.

2024-05-30 02:30 UTC, lazaroysr96 commented on src/components/Slider.tsx
> +  onProgressChange: (value: number) => void
?????????

2024-05-31 17:54 UTC, yurixander approved these changes

2024-05-31 17:54 UTC, merged