feat: Implement new `Roster` component
yurixander/mirage pull request #40
Opened 2024-05-15 18:22 UTC by criss8X

### Aquí estare implementando el nuevo diseño, y la nueva funcionalidad del Roster

-[x] Roster User (nuevo diseño)

-[] Diseño de listado de miembros

-[] Implementar funcionalidad de obtener el last presence age

2024-05-19 22:36 UTC, yurixander approved these changes

2024-05-19 23:12 UTC, lazaroysr96 requested changes

2024-05-19 23:12 UTC, lazaroysr96 commented on src/containers/Roster/Roster.tsx
> +              <Typography className="ml-1 w-full text-lg text-neutral-600">
Aca yo creo que es mejor añadir más variantes al componente Typography, digamos una variante para el estilo text-lg que pusiste ahí, mi idea es hacer un poco de POO, con Typography.

2024-05-19 23:30 UTC, lazaroysr96 commented on src/containers/Roster/RosterUser.tsx
> +        <Typography className="line-clamp-1" variant={TypographyVariant.P}>
Ésto es indirecto a este componente, creo que un mejor nombre para TypographyVariant.P sería TypographyVariant.Small, resulta un tanto más semántico, a la larga escribir código poco semántico podría complicar el mantenimiento del código.

2024-05-19 23:51 UTC, lazaroysr96 commented on src/hooks/matrix/useRoomMembers.ts
> +import {useEffect, useState, useCallback} from "react"
Curiosamente aquí ni hay exactamente un cambio, simplemente se movió useCallback del principio al final.

2024-05-20 02:47 UTC, criss8X commented on src/containers/Roster/Roster.tsx
> +              <Typography className="ml-1 w-full text-lg text-neutral-600">
Es cierto, lo pensé, pero que variante agregarias si ya estan?, revisare

2024-05-20 04:51 UTC, lazaroysr96 requested changes
Algo parece no ir del todo bien con storybook en esta raiz, asegúrate de que StoryBook, esté funcionando.

2024-05-20 16:22 UTC, lazaroysr96 approved these changes

2024-05-21 14:29 UTC, merged