Create Component CallModal
yurixander/mirage pull request #41
Opened 2024-05-20 04:29 UTC by lazaroysr96

## Creando Componente CallModal

Desarrolle lo referente a la interfaz del componente CallModal, quedo a la espera de su revisión para añadir cambios, noten que no se ha implementado ninguna funcionalidad aún, queda pendiente una tarea para implementar la lógica de este componente.

- [ ]  ver que pasa con storybook

2024-05-22 22:02 UTC, criss8X requested changes

2024-05-22 22:02 UTC, criss8X commented on src/components/CallModal.tsx
> +          <div>
Div redundante

2024-05-22 22:02 UTC, criss8X commented on src/components/CallModal.tsx
> +            color="#000000"
El color usa nombres explícitos, white, dark

2024-05-23 02:27 UTC, lazaroysr96 commented on src/components/CallModal.tsx
> +  FaWrench,
son los que coinciden 100% con los iconos del diseño.

2024-05-23 02:31 UTC, criss8X commented on src/components/CallModal.tsx
> +  FaWrench,
Pero es que yo llevo desde hace semanas diciendo que los iconos del diseño están mal

2024-05-23 02:31 UTC, criss8X commented on src/components/CallModal.tsx
> +  FaWrench,
Hay que buscar un equivalente

2024-06-03 05:16 UTC, yurixander requested changes

2024-06-03 05:16 UTC, yurixander commented on src/components/CallModal.tsx
> +                  : ""}
Usa un `switch` en una funcion aparte en vez de hacerlo asi, asi evitas el `""` al final (podria causar problemas si mas variantes se agregan, sin embargo al usar `switch` el te da un error si falta una variante, lo cual es bueno).

2024-06-03 05:16 UTC, yurixander commented on src/components/CallModal.tsx
> +        tooltip="Calling"
`Calling` -> `Accept`

2024-06-03 05:16 UTC, yurixander commented on src/components/CallModal.tsx
> +        tooltip="Call off"
`Call off` -> `Decline`

2024-06-03 05:16 UTC, yurixander commented on src/components/CallModal.tsx
> +  const [isCallPause, setIsCallPause] = useState(false)
isCallPause**d**, con `d`

2024-06-03 05:16 UTC, yurixander commented on src/components/CallModal.tsx
> +        tooltip="Mic off"
No es solo para apagarlo, es para encender/apagar dependiendo de su estado actual. Por lo tanto, `Mic off` -> `Toggle microphone`

2024-06-03 05:16 UTC, yurixander commented on src/components/CallModal.tsx
> +        tooltip="Audio"
`Audio` -> `Toggle speaker`

2024-06-03 05:16 UTC, yurixander commented on src/components/CallModal.tsx
> +      />
Pon el `tooltip` y `Icon` dynamicos dependiendo de el estado, si esta pausado pon el icono Play y tooltip `Play`, y asi la misma idea si no lo esta

2024-06-04 16:53 UTC, criss8X commented on src/components/CallModal.tsx
> +  avatarUrl?: string
props que pueden ser undefined siempre al final (comentario normal no es obligatorio)

2024-06-04 17:07 UTC, criss8X requested changes
Necesitas resolver también algunas advertencias de comentarios en ingles redundantes o mal escritos que el mismo eslint esta notificando, algunas cosas mas y queda listo el componente

2024-06-07 05:11 UTC, yurixander approved these changes

2024-06-07 05:42 UTC, yurixander requested changes

2024-06-07 05:42 UTC, yurixander commented on src/components/CallModal.tsx
> +    }
Si ya cubriste todas las opciones posibles, puedes omitir el `default`

2024-06-07 05:42 UTC, yurixander commented on src/components/CallModal.tsx
> +          isSpeacker ? "bg-purple-400 hover:bg-purple-300" : "bg-slate-100"
`isSpeacker` -> `isSpeakerMode`

2024-06-07 05:42 UTC, yurixander commented on src/components/CallModal.tsx
> +  const [micState, setMicState] = useState(true)
`micState` -> `isMicEnabled`

2024-06-08 12:53 UTC, yurixander approved these changes

2024-06-08 13:48 UTC, criss8X approved these changes

2024-06-09 01:25 UTC, merged