Cristian/upgrade-components
yurixander/mirage pull request #42
Opened 2024-05-21 18:08 UTC by criss8X

## Aquí estare haciendo retoques visuales y añadir lo que no se habia hecho en el diseño

2024-05-26 17:58 UTC, yurixander requested changes

2024-05-26 17:58 UTC, yurixander commented on src/containers/NavigationSection/modals/DirectMessageModal.tsx
> +                    }
Pon el children dentro en vez de un prop

2024-05-27 15:51 UTC, yurixander approved these changes

2024-05-28 05:15 UTC, lazaroysr96 requested changes

2024-05-28 05:15 UTC, lazaroysr96 commented on src/components/Button.tsx
> +      disabled={isLoading === true || isDisabled === true}
Por que estas utilizando ===true, si ambos ya son booleans???

2024-05-28 05:26 UTC, lazaroysr96 approved these changes

2024-05-28 06:33 UTC, merged