refactor: Code cleanup & typography improvements
yurixander/mirage pull request #45
Opened 2024-06-02 04:06 UTC by yurixander

2024-06-03 00:36 UTC, criss8X approved these changes

2024-06-04 10:44 UTC, lazaroysr96 submitted a review, later dismissed

2024-06-04 16:28 UTC, criss8X requested changes
En si los problemas siguientes son cuestion visual de tamaño de texto.

Hay componentes rotos:
`Context Menu`
![image](https://github.com/yurixander/mirage/assets/100869331/c25cf190-a37b-4eec-9e39-8ec9dd2b47fe)

`Direct Message` (Los tamaños de texto contra otros componentes no combinan)
![image](https://github.com/yurixander/mirage/assets/100869331/62eceb53-53c5-4469-bd5d-99f8038e8f0e)

`UserBar` Supongo que el ``line-height` hizo de las suyas aqui y rompio visualmente esto:

![image](https://github.com/yurixander/mirage/assets/100869331/8e1489e9-9e20-42a9-981d-951e4b17e483)

`RoomChildList`: Textos grandes

![image](https://github.com/yurixander/mirage/assets/100869331/a32e9484-fd8f-4710-82cd-60c312bfb972)

Vista general inconsitente en tamaño:
![image](https://github.com/yurixander/mirage/assets/100869331/01f7475c-e5ba-462b-b38d-850e017ab398)

El `Roster` el last precense no se ve (se puede solucionar con un tooltip de hecho lo debe llevar cuando se pongan los tooltip ) pero aun asi es inconsistente con lo demas:

![image](https://github.com/yurixander/mirage/assets/100869331/45fc3108-0a1a-4510-868b-7ebd93fabff8)

2024-06-07 12:58 UTC, criss8X approved these changes

2024-06-08 03:58 UTC, lazaroysr96 requested changes
Tienes conflictos sin resolver.

2024-06-09 01:26 UTC, yurixander commented
Conflictos @criss8X

2024-06-13 14:32 UTC, lazaroysr96 approved these changes

2024-06-13 14:35 UTC, merged