Criss/new-modal-handling
yurixander/mirage pull request #48
Opened 2024-06-05 06:37 UTC by criss8X

## Implementacion de un nuevo Modal

### Progress:

 - [x] Implementacion de una nueva logica del `Modal`
 - [ ] Implementacion de un nuevo diseño del Modal

- Contexto Global Modal: Ahora el modal usa contexto global.
- El componente se llama 1 sola vez, y en este caso en ´app.tsx´
- No es necesario declarar el componente en cada modal, solo agregas un nuevo elemento al enum `Modals` y pones su declaracion en modalElements.
- Ahora solo con usar el hook `useActiveModal` puedes lanzar un modal desde cualquier punto.

2024-06-05 19:49 UTC, yurixander approved these changes

2024-06-07 03:20 UTC, lazaroysr96 submitted a review, later dismissed

2024-06-07 04:51 UTC, yurixander commented
Unos conflictos aqui @criss8X

2024-06-07 22:24 UTC, yurixander approved these changes

2024-06-08 04:03 UTC, lazaroysr96 requested changes

2024-06-08 04:03 UTC, lazaroysr96 commented on src/components/Modal.tsx
> +          variant={TypographyVariant.H4}
Si no me equivoco el componente typography fue actualizado y la variante puede que ya no sea H4

2024-06-08 12:40 UTC, lazaroysr96 approved these changes

2024-06-08 12:52 UTC, merged