Lazaroysr96/update slider
yurixander/mirage pull request #51
Opened 2024-06-13 04:10 UTC by lazaroysr96

### Add tag to Slider
![slider-3](https://github.com/yurixander/mirage/assets/156694602/e420c549-a818-4d85-bd2b-8d5803a748ab)

2024-06-13 13:56 UTC, yurixander approved these changes

2024-06-14 03:48 UTC, criss8X requested changes
Marcha muy bien, solo que aqui esta disparejo el tooltip cuando lo estuve probando,

![image](https://github.com/yurixander/mirage/assets/100869331/0d109ddf-af16-4dac-85de-eddd634a7f7a)

2024-06-14 03:48 UTC, criss8X commented on src/components/Slider.tsx
> +        className="slider absolute h-3 w-60 cursor-pointer appearance-none rounded-full bg-transparent p-0"
Aqui el slider una clase custom no creo que sea necesaria en este caso, mejor usa en tailwindcss el selector input[type="range"]::cosacustom-que-no-este-en-tailwindcss

2024-06-14 03:48 UTC, criss8X commented on src/components/Slider.tsx
> +        className="h-3 bg-fuchsia-400 shadow"
Los colores siempre priorizar un patron en este caso es color de asento, si se va a cambiar el color, en este caso a fuchsia deberia ser fuchsia-500

2024-06-14 03:48 UTC, criss8X commented on src/components/Slider.tsx
>        {step.map((_opt, index) => (
Para evitar aqui usar un _opt y hacerlo mas limpio, mejor usa algo como esto:

```ts
const step = Array.from(
    {length: count},
    (_, num) => num 
  )
```

Eso es para el for que estas haciendo arriba

2024-06-14 12:15 UTC, lazaroysr96 commented on src/components/Slider.tsx
> +        className="slider absolute h-3 w-60 cursor-pointer appearance-none rounded-full bg-transparent p-0"
O sea que aplique esto de forma global a todos los input del tipo range?

2024-06-16 14:29 UTC, yurixander approved these changes

2024-06-17 17:18 UTC, criss8X requested changes
Te falta añadir la version con tooltip

2024-06-17 17:18 UTC, criss8X commented on src/components/Slider.tsx
> +  isTooltip?: boolean
No puedes decir que el slider es un Tooltip, el `isTooltip` esta mal en este caso, tiene que ser algo como, contiene un tooltip, aqui si puedes gestionar con variantes (no es obligado, puede hacerse con props, pero por si acaso te cuadra mas una variante), un enumerado para un Slider con tooltip y otro para el slider normal, en el slider que tiene tooltip, el tooltip no debe mostrarse siempre, debe mostrarse solamente cuando arrastras para mostrar el numero y que cuando sueltes se quite

2024-06-17 18:46 UTC, yurixander commented
> Te falta añadir la version con tooltip

Nos deshacemos del tooltip

2024-06-18 13:32 UTC, criss8X commented
> > Te falta añadir la version con tooltip
> 
> Nos deshacemos del tooltip

Entonces deberia de borrar la prop que dice isTooltip

2024-06-20 18:54 UTC, criss8X requested changes
Revisar lo del width, y de paso ver porque estas tirando el mismo className del padre a todos los componentes hijos.

2024-06-20 18:54 UTC, criss8X commented on src/components/Slider.tsx
> +          width={className}
width, y le pasas className,

Veo problemas futuros con esto, se cual es tu intencion pero esto no puede ir asi por:
Le asignas un className a algo que se supone que es el ancho, le estas tirando estilo de colores y todo, ahi hay posibilidad de meterle cualquier estilo y no solo el width por eso veo que es un gran problema.

2024-06-20 18:54 UTC, criss8X commented on src/components/Slider.tsx
> +        <StepProgressBar width={className} steps={(max - min) / step} />
aqui nuevamente un width que dara problemas

2024-06-23 17:11 UTC, criss8X requested changes
Cuando es al frente tiene un problema que le falta recorrido asi:
![image](https://github.com/yurixander/mirage/assets/100869331/d5a3666a-35f2-4441-98ed-a74927b3938f)


Cuando esta muy al final le sobra recorrido:
![image](https://github.com/yurixander/mirage/assets/100869331/6b65ad0f-b72b-4dc2-86f1-c83f90320151)


Y los diseños que hiciste en codigo no se parecen al diseño que pusiste aqui en el PR al inicio como descripcion (se que el diseño cambio y no lleva tooltip, pero en la descripcion del PR debe ir la foto de como quedo en codigo y no la foto de el diseño de figma).

![image](https://github.com/yurixander/mirage/assets/100869331/bd0e6e75-c9fc-4155-b957-831d73b0e935)

2024-06-23 17:11 UTC, criss8X commented on src/components/Slider.tsx
> +      style={{width: width}}
Tienes aqui un Warring

2024-07-01 01:26 UTC, criss8X requested changes

2024-07-01 01:26 UTC, criss8X commented on src/components/Slider.tsx
> +const BasicProgressBar: FC<{progress: number; w: number}> = ({progress, w}) => {
w es una letra muy simple, es confuso aunque sea una gestion interna, si quieres en este caso usa types para las props para que no te enredes tanto con las props y los nombres que estoy viendo

2024-07-01 01:26 UTC, criss8X commented on src/components/Slider.tsx
> +  return elemnt === undefined
nombres de variables mal, en vez de elemnt es `element`

2024-07-01 01:26 UTC, criss8X commented on src/components/Slider.tsx
> +const getElementSize = (elemnt?: Element | null) => {
En este getElementSize se puede hacer de una mejor manera aquí te cuento las irregularidades que tiene este metodo contra el que te dare mas abajo:

1. Estas usando un elemento en general `Element` que encima que lo tratas como nulo le pones undefined también, 2 estdos `undefined` y ``null` para un elemento importante.
2. Necesitas obtener de la ventana `window` el ComputedStyle de un elemento que anteriormente tienes que checkear valores para ver si es nulo y tirar numeros que son correctos pero son manuales y que dependen de la densidad de pantalla o de la amplitud de la ventana del navegador.

### Solucion o Mejora :

Para estos casos se usa algo llamado `ref`, la referencia para obtener sus propiedades y interactuar con un HTMLElement.

````ts
const labelRef = useRef<HTMLLabelElement>(null)

<label ref={labelRef} />```

Luego para obtener el width podrias hacer algo como:

```ts
const labelWidth = labelRef.current?.clientWidth ?? (number en caso de ser null el labelRef)```

Obviamente eso debe hacerse un checkeo antes si labelRef.current es nulo, pero bueno ya con esto puedes mejorar eso.

2024-07-19 04:20 UTC, criss8X approved these changes

2024-07-20 11:46 UTC, merged