feat: Revise all components and hooks
yurixander/mirage pull request #53
Opened 2024-06-19 22:38 UTC by criss8X

## Aqui estare resolviendo cualquier problema existente, y revisando que todo este en orden.

### Si existe alguna actualizacion la pondre por aqui:

2024-06-20 06:05 UTC, yurixander requested changes

2024-06-20 06:05 UTC, yurixander commented on src/containers/NavigationSection/modals/DirectMessageModal.tsx
>            {timeFormatter(lastMessageSentDate)}
timeFormatter -> formatTime

2024-06-20 06:05 UTC, yurixander commented on src/containers/NavigationSection/modals/DirectMessageModal.tsx
>            {timeFormatter(lastMessageSentDate)}
Usar verbo siempre para nombre de funciones

2024-06-20 16:48 UTC, criss8X commented on src/components/ImageMessage.tsx
> +        <ContextMenu id={generateUniqueNumber()} elements={contextMenuItems}>
Oo entiendo, me pongo a trabajar en eso

2024-06-22 17:54 UTC, lazaroysr96 approved these changes

2024-06-22 18:04 UTC, merged