Create Component FileMessage
yurixander/mirage pull request #58
Opened 2024-07-01 03:27 UTC by lazaroysr96

## Creando Componente FileMssage

Este componente será empleado para los casos en que el usuario reciba un determinado archivo.
![Screenshot 2024-06-30 at 23-10-52 Mirage — Matrix web client](https://github.com/yurixander/mirage/assets/156694602/02489a2c-2561-4a98-884c-d60f9a707fbc)

- [ ] Añadir funciones útiles.

2024-07-27 19:00 UTC, yurixander requested changes

2024-07-27 19:00 UTC, yurixander commented on src/components/FileMessage.tsx
> +          </div>
Recuerda poner siempre linea blanca entre elementos hermanos bajo el mismo padre

2024-07-27 19:15 UTC, lazaroysr96 commented on src/components/FileMessage.tsx
> +      onAuthorClick={() => {}}
Estas son heredadas del componente MessageContainer

2024-07-27 21:15 UTC, lazaroysr96 commented on src/components/FileMessage.tsx
> +  return "0 B"
Ahora en vez de 0 B devolverá 1024+ TB. Aunque abría que ver cuál es el tamaño máximo para un archivo permitido en Matrix

2024-07-27 21:20 UTC, yurixander requested changes

2024-07-27 21:20 UTC, yurixander commented on src/components/FileMessage.tsx
> +const fileSizeToString = (fileSize: number) => {
Evitar esto, porque no pones tipo de retorno string?

2024-07-27 21:56 UTC, criss8X submitted a review, later dismissed
A la hora de solucionar ten en cuenta que:

1. Los archivos no tendran mas de 1Gb de tamaño, el tamaño maximo a mostrar será en `Mb`
2. La descarga del documento no tendra un progreso, el progreso lo maneja el navegador, cuando le das en el icono de descargar lo va a descargar como lo descarga el navegador normalmente.

2024-07-27 21:56 UTC, criss8X commented on src/components/FileMessage.tsx
> +    const size = fileSize / KB
y aqui ya ponlo entre parentesis ´(fileFize / KB).toFixed(2)´

2024-07-27 21:56 UTC, criss8X commented on src/components/FileMessage.tsx
> +    return size.toFixed(2) + " MB"
Lo mismo que el de arriba

2024-07-27 21:56 UTC, criss8X commented on src/components/FileMessage.tsx
> +  return "0 B"
En lugar de un if else y al final retornar 0 (El error que te comento @yurixander abajo), te recomiendo mejor que gestiones solo hasta MB  como mencione arriba la subida al servidor de archivos es pequeña no va a llegar a 1tb creo que son 200Mb , entonces haces:

Si es menor a Kb entonces calculas para `bytes`
Si es mayor a `Kb` y menor que `MB` entonces calculas para `kbytes`
Si es mayor a MB (osea un else al final) entonces calculas a `Mbytes`

Y listo siempre retornas un valor correcto, no puedes retornar un 0 ni valores vacios.

2024-07-27 21:56 UTC, criss8X commented on src/components/FileMessage.tsx
> +}
Usa una constante para el size, 

```ts
const ICON_SIZE = 20
```

2024-07-27 21:56 UTC, criss8X commented on src/components/MessageContainer.tsx
> +            <time className="min-w-16 text-right text-gray-300">
porque `text-right` aqui si el contenedor padre tiene un `justify-between` ?

2024-07-27 21:56 UTC, criss8X commented on src/components/FileMessage.tsx
> +}
Aqui puedes usar <MessageContainer>Contenido aqui</MessageContainer>

en lugar de usar el children

2024-07-27 21:56 UTC, criss8X commented on src/components/FileMessage.tsx
> +    }
Usa una constante para almacenar el valor de size,

```ts
const ICON_SIZE = 20
 ```

2024-07-28 03:22 UTC, lazaroysr96 commented on src/components/MessageContainer.tsx
> +            <time className="min-w-16 text-right text-gray-300">
esto es por que time tiene un tamaño mínimo establecido, entonces esta propiedad permite que el contenido dentro de time se alinee a la izquierda ya que podría no heredar la propiedad del padre.

2024-07-28 19:44 UTC, yurixander approved these changes

2024-07-28 19:45 UTC, merged