feat: Implement new `Navigation` component
yurixander/mirage pull request #60
Opened 2024-07-12 22:58 UTC by criss8X

## Implementar la nueva seccion de navegación

### Progress:

 - [x] Implementar `Space` component
 - [ ] Implementar lista de espacios `SpaceList`

Space Component => 
![image](https://github.com/user-attachments/assets/91c14697-4320-4518-85f2-7035fc538a72)

2024-07-18 20:39 UTC, lazaroysr96 requested changes

2024-07-18 20:39 UTC, lazaroysr96 commented on src/components/AppLogo.tsx
> +        style={{color: "#D64DF4", textShadow: "#d54df433 0 1px 0"}}>
Veo que aquí estás utilizando estilos en linea, revisa a ver si se puede hacer con TailWind

2024-07-18 21:14 UTC, lazaroysr96 commented on src/containers/NavigationSection/hooks/useSpaces.ts
> +    avatarUrl: getImageUrl(space.getMxcAvatarUrl(), space.client),
Aquí en vez de getMxc podría ser getMtx

2024-07-18 21:15 UTC, lazaroysr96 commented on src/containers/NavigationSection/Space.tsx
> +          "group box-border size-10 cursor-pointer overflow-hidden rounded-lg border-[3px] transition-colors",
border-[3px] Supongo que sea por que específicamente debe ser a 3px, no obstante si se puede usar algún valor normal de TailWind, úsalo.

2024-07-18 21:15 UTC, lazaroysr96 commented on src/containers/NavigationSection/NavigationSection.tsx
> +            style={{color: "#D64DF4"}}>
Aquí también veo estilos en línea.

2024-07-19 04:23 UTC, criss8X commented on src/components/AppLogo.tsx
> +        style={{color: "#D64DF4", textShadow: "#d54df433 0 1px 0"}}>
No los hay, eso es propio del diseño base, en el propio diseño base no hay estilos de tailwindcss porque es algo específico, en ese caso va bien.

2024-07-19 04:25 UTC, criss8X commented on src/containers/NavigationSection/hooks/useSpaces.ts
> +    avatarUrl: getImageUrl(space.getMxcAvatarUrl(), space.client),
Eso es una función de matrix sdk js no es una función que haya hecho yo, en todo caso el nombre es Mxc porque va de Matrix Client por eso las siglas.

2024-07-19 04:25 UTC, criss8X commented on src/containers/NavigationSection/Space.tsx
> +          "group box-border size-10 cursor-pointer overflow-hidden rounded-lg border-[3px] transition-colors",
Debe ser específicamente 3 no puede ser otro valor

2024-07-19 04:26 UTC, criss8X commented on src/containers/NavigationSection/RoomChildList.tsx
Si, no importa este PR lo tengo en Draft pero lo pusieron el listo para revisión cuando no estaba listo para revisión. Por eso es posible que veas alertas, yo las arreglo

2024-07-19 04:27 UTC, criss8X commented on src/containers/NavigationSection/NavigationSection.tsx
> +            style={{color: "#D64DF4"}}>
También va de el color de el diseño base, en el diseño base tienen color custom que es el que pega, solo sigo los patrones que tienen en el diseño

2024-07-19 04:28 UTC, criss8X commented on src/containers/NavigationSection/NavigationSection.tsx
> +            style={{color: "#D64DF4"}}>
Si aquí pongo un color custom de taiwlindcss que se parezca y en el otro (por obligacion) uso el color original de el diseño se verá raro por eso pongo el mismo que el diseño base

2024-07-23 01:18 UTC, yurixander approved these changes

2024-07-23 01:19 UTC, yurixander commented
Conflictos @criss8X

2024-07-27 06:49 UTC, lazaroysr96 approved these changes

2024-07-27 18:55 UTC, merged