feat: Implement new `ChatInput` component
yurixander/mirage pull request #64
Opened 2024-07-28 23:17 UTC by criss8X

## Title of what you did.

### Progress:

 - [ ] Implementar nuevo text area para `ChatInput`
 - [ ] Implementar nueva interfaz para `ChatInput`
 - [ ] Actualizar logica para `ChatInput`

2024-07-29 19:52 UTC, yurixander requested changes

2024-07-29 19:52 UTC, yurixander commented on src/containers/RoomContainer/ChatInput.tsx
> +          )}
Aqui se le puede quitar el `twMerge`?

2024-07-29 19:52 UTC, yurixander commented on src/containers/RoomContainer/ChatInput.tsx
> +const BUTTON_SIZE = "size-5 md:size-7"
`BUTTON_SIZE` -> `BUTTON_SIZE_CLASS`

2024-07-30 00:59 UTC, lazaroysr96 approved these changes
Todo bien, todo correcto, salvo los comentarios pendientes por resolver.

2024-07-30 08:50 UTC, yurixander approved these changes

2024-07-30 16:08 UTC, criss8X commented on src/containers/RoomContainer/ChatInput.tsx
> +          )}
Si bro, lo hice para acomodarlo mejor, tener la responsividad aparte

2024-07-30 16:51 UTC, merged