feat: Implement ReplyMessage
yurixander/mirage pull request #65
Opened 2024-08-01 03:40 UTC by lazaroysr96

## Implementando ReplyMessage

Implementación del componente ReplyMessage, este componente es usado para responder al mensaje de otro usuario.

![Screenshot 2024-07-31 at 23-21-23 Mirage — Matrix web client](https://github.com/user-attachments/assets/6a2144a1-246f-44c2-a2ed-ce298ca97ec8)

2024-08-01 13:20 UTC, criss8X reviewed
Solo lo que mencione de el `fromMessage`

2024-08-01 13:20 UTC, criss8X commented on src/components/ReplyMessage.tsx
> +  fromMessage: MessageBaseProps
Esta interesante esto, hay que valorar si es mejor usar esto o usar un `id`

@yurixander que crees?

2024-08-01 14:10 UTC, lazaroysr96 commented on src/components/ReplyMessage.tsx
> +  fromMessage: MessageBaseProps
fromMessage es un prop que recibe las características del mensaje al que se está respondiendo para incluir los datos necesarios a mostrar.

2024-08-02 06:09 UTC, yurixander commented
Esto puede funcionar, pero creo que poniendo un id seria mas simple

2024-08-02 06:09 UTC, yurixander commented on src/components/ReplyMessage.tsx
> +  fromMessage: MessageBaseProps
Esto puede funcionar, pero creo que poniendo un id seria mas simple

2024-08-02 06:10 UTC, yurixander commented on src/components/ReplyMessage.tsx
> +  fromMessage: MessageBaseProps
El problema seria como obtener ese otro mensaje dado un id

2024-08-02 15:29 UTC, criss8X commented on src/components/ReplyMessage.tsx
> +  fromMessage: MessageBaseProps
Facil, el id de cada mensaje es el event_id de cada mensaje

2024-08-02 15:30 UTC, criss8X commented on src/components/ReplyMessage.tsx
> +  fromMessage: MessageBaseProps
Lo que le comente a Lazaro es que las props y la gestion de esos componentes el la debe hacer basandose en lo que matrix devuelve 

Que revise el json del evento que devuelve matrix y vea cuales son las props

2024-08-06 15:32 UTC, criss8X commented
Que le falta a esto @lazaroysr96 ???

2024-08-07 23:06 UTC, yurixander commented on src/components/ReplyMessage.tsx
> +  fromMessage: MessageBaseProps
Resolver este comentario @lazaroysr96

2024-08-08 14:13 UTC, criss8X requested changes

2024-08-08 14:13 UTC, criss8X commented on src/components/ReplyMessage.tsx
> +            {fromMessage.text.slice(0, 50)}
aunque esto tienes que cambiar el fromMessage para usar un `id` aqui de igual forma tendras que obtener el mensaje anterior y hacerle el slice aqui, pero:

En tailwindcss puedes usar un estilo que cuando el componente alcance su max-width ponga 3 puntos , creo que es lo mas conveniente en este caso, en lugar de hacer un `slice` sin mostrar al usuario que ese contenido es mas grande, en otro caso habria que al hacer el `slice` ponerle 3 puntos al final indicando que hay mas contenido, comprobar la longitud para ver si aplica hacerle el `slice` ect... osea demaciada gestion.

Mejor usa esa propiedad `line-clamp-1` con un `max-width `

2024-08-08 14:13 UTC, criss8X commented on src/components/ReplyMessage.tsx
> +      />
Recien cambio la prop `id` por `messageId` para que sea mas descriptiva, ya los cambios estan en la rama `dev`

2024-08-12 04:27 UTC, yurixander approved these changes

2024-08-13 01:30 UTC, criss8X requested changes

2024-08-13 01:30 UTC, criss8X commented on src/components/ReplyMessage.tsx
> +  onSecondaryMessageClick: () => void
El termino Secondary aqui esta mal empleado

2024-08-13 01:30 UTC, criss8X commented on src/components/ReplyMessage.tsx
> +  secondaryAvatarUrl?: string
Igual que en estos, los nombres no son descriptivos

2024-08-13 01:30 UTC, criss8X commented on src/components/ReplyMessage.tsx
> +  onSecondaryMessageClick: () => void
en este click debe admitir un `(eventId: string) => void`

2024-08-13 01:30 UTC, criss8X commented on src/components/ReplyMessage.tsx
> +}
Lo mismo de arriba

2024-08-13 01:30 UTC, criss8X commented on src/containers/RoomContainer/ChatMessages.tsx
> +      // eslint-disable-next-line sonarjs/cognitive-complexity
@yurixander Este creo que habria que permitirlo en este caso, ya que indica que ese if else es demaciado grande, y ver como le hacemos, si no el PR se nos vuelve gigante.

Con que @lazaroysr96 Ponga un TODO aqui indicando que eso hay que resolverlo creo que tiene que tu crees @yurixander ??

2024-08-13 01:30 UTC, criss8X commented on src/utils/rooms.ts
> +      const relates = eventContent["m.relates_to"]
m.relates_to tiene un tipo creo en matrix, en lugar de usar el literal ahi

2024-08-13 01:30 UTC, criss8X commented on src/utils/rooms.ts
> +      const relates = eventContent["m.relates_to"]
tiene un Enum creo

2024-08-13 01:30 UTC, criss8X commented on src/utils/rooms.ts
> +        const reply = relates["m.in_reply_to"]
debe haber otro enum para el m.in_reply_to

2024-08-13 01:30 UTC, criss8X commented on src/utils/util.ts
> +  return body.slice(index + 2, body.length)
y si no hay \n\n que pasa? ya has probado

2024-08-13 01:30 UTC, criss8X commented on src/utils/util.ts
> +  return body.slice(index + 2, body.length)
Tamvien si el index + 2 se pasa del body.length no daria un error eso ?

2024-08-13 01:30 UTC, criss8X commented on src/utils/util.ts
> +  let match = body.split(/\n{2}/)[0]
si cuando haces `[0]` la lista de `strings` que devuelve `split` es 0 va a dar un error al intentar acceder a un elemento `undefined` en el match siguente

2024-08-13 01:30 UTC, criss8X commented on src/utils/util.ts
> +  match = match.slice(match.indexOf(">", match.indexOf("<")) + 1, match.length)
Igual aqui debes ver que cuando esos indices esten bien y que cuando le hagas el + 1 no se pase de match.length, quizas un `Math.minOf()` pueda resolverte.

2024-08-13 01:30 UTC, criss8X commented on src/utils/util.ts
> +  let match = body.split(/\n{2}/)[0]
Lo mismo, cuando accedes a un elemento de una lista como aqui, y abajo usas ese elemento si es undefined dara error

2024-08-16 03:53 UTC, lazaroysr96 commented
Últimos cambios:
- Se añadido un archivo a útil con las funciones necesarias para procesar el ReplyMessage
- Se creó una función para validar los ReplyMessage. 
- Se solucionó problema en el ZoomImage, anteriormente cuando abrías una imagen está se intentaba mostrar a su resolución normal, como resultado se salía de los límites de la pantalla. 
- Se solucionó problema con el AvatarImage que causaba que no se mostrara el efecto de borde redondeado en las imágenes de los Avatars.

2024-08-16 16:00 UTC, criss8X requested changes

2024-08-17 04:05 UTC, lazaroysr96 commented
### Últimos cambios
- Se mejoró la gestión de la obtención del nombre del usuario al que se está respondiendo. 
- Se creó una función en la que a futuro se deberá implementar la lógica de que pasará cuando demos en el mensaje al que se está respondiendo en el ReplyMessage. 

⚠️ Importante:
Cuando se valla a implementar la lógica de que hacer al dar click en el ReplyMessage para ir al mensaje al que se está respondiendo, debemos tener en cuenta que cuando no sea posible obtener el ID del evento al que se está respondiendo (algo que normalmente no debe de pasar) si no existe ID se devolverá "" por lo que hay que getinar con un ir ni hacer nada en caso de que ID sea igual a ""

2024-08-18 14:31 UTC, lazaroysr96 commented on src/utils/parseReply.ts
> +}
Por una cuestión de organización y legibilidad creo que es mejor que estén separadas, de ese modo queda mas claro que realizar cada bloque de código.

2024-08-18 15:16 UTC, criss8X requested changes

2024-08-18 15:16 UTC, criss8X commented on src/containers/RoomContainer/ChatMessages.tsx
> +            }}
Ponle la funcion onAuthorClick de arriba

2024-08-18 15:16 UTC, criss8X commented on src/utils/parseReply.ts
> +  return match
espacio

2024-08-18 15:16 UTC, criss8X commented on src/utils/parseReply.ts
> +  match = match.slice(
espacio

2024-08-18 15:16 UTC, criss8X commented on src/utils/parseReply.ts
> +}
Como te mensiono, todo lo puedes hacer en 1 sola funcion, es mejor que estar partiendo todo en varias funciones que luego es complicado para estar buscando aunque esten juntas (suena estupido pero es cierto), si en el futuro se pueden reutilizar esas funciones pues se extraen y se reutilizan de forma tal que sirvan para todos, si no pues todo se queda bajo la misma funcion

2024-08-18 15:16 UTC, criss8X commented on src/utils/rooms.ts
> +  // eslint-disable-next-line sonarjs/cognitive-complexity
esto esta resuelto en los cambios en dev, debes hacer merge dev y quitar estos comentarios

2024-08-18 15:26 UTC, criss8X requested changes

2024-08-18 15:26 UTC, criss8X commented on src/utils/rooms.ts
> +              quotedMessageId: reply.event_id ?? "",
esto aqui no puede ser, no puedes tirar un string vacio eso es un problema a futuro, osea evita al 99% hacer esto

2024-08-18 15:26 UTC, criss8X commented on src/utils/rooms.ts
> +              quotedMessageId: reply.event_id ?? "",
Debes implementar alguna logica que si el eventId del mensaje al cual se esta respondiendo no esta, pues que no le permita al usuario hacer click

2024-08-18 15:26 UTC, criss8X commented on src/utils/rooms.ts
> +              quotedMessageId: reply.event_id ?? "",
O que muestre un Toast o mensaje de error que cuando el usuario haga click y el eventId de ese mensaje al que se le hace reply diga que no se ha podido encontrar ese mensaje

2024-08-18 15:26 UTC, criss8X commented on src/utils/rooms.ts
> +              quotedMessageId: reply.event_id ?? "",
No debes buscar ninguna libreria para Toast eso sera despues, solo en caso de hacer lo del toast poner un TODO que diga que en ese lugar se debe lanzar un toast de ect...

2024-08-18 15:28 UTC, criss8X requested changes
Cambiale el nombre al archivo parseReply y ponle o `parsers` o `parser` o `messages`

2024-08-19 11:54 UTC, criss8X approved these changes

2024-08-19 11:54 UTC, merged