Imolement FileMessage and FilePreview
yurixander/mirage pull request #72
Opened 2024-08-06 12:26 UTC by lazaroysr96

## Implementación de FileMessage y FilePreview.

En este PR se estará Implementando el Componente FileMessage en el Chat, además de eso se trabajará en la implementación de FilePreview y todo lo relacionado con la subida de archivos. 

- [ ] Implementación de FileMessage en el Chat
- [ ] Implementar FilePreview
- [ ] Implementar Subida de Archivos
- [ ] Implementar descarga de archivos.

2024-08-06 15:18 UTC, criss8X commented
Para la subida de archivos hay una funcion creada en `utils.ts` revisala

2024-08-06 15:45 UTC, lazaroysr96 commented
Resta implementarlo en el Chat
@criss8X

2024-08-07 23:05 UTC, yurixander requested changes

2024-08-07 23:05 UTC, yurixander commented on src/components/FileMessage.tsx
> +    return fileName.substring(p, fileName.length)
Mejorar nombre de variable `p`, siempre usar nombres descriptivos en vez de letras.

2024-08-07 23:05 UTC, yurixander commented on src/components/FileMessage.tsx
> +  } else {
Explicar en comentarios breves la logica de el `if` y `else`, ya que no es tan claro en este caso

2024-08-07 23:05 UTC, yurixander commented on src/components/FileMessage.tsx
> +    // eslint-disable-next-line unicorn/prefer-string-slice
Evitar usar `eslint-disable-...`, seguir la sugerencia del lint

2024-08-07 23:05 UTC, yurixander commented on src/utils/rooms.ts
> +      console.log(eventContent)
Remover `console.log`s de prueba

2024-08-08 01:29 UTC, criss8X requested changes
Todavía no he revisado bien a fondo porque ando desde el móvil pero ahí tienes algunas cosas

2024-08-08 01:29 UTC, criss8X commented on src/components/FileMessage.tsx
>    uploadProgress?: number
Porque tiene un upload progress.un componente que se basa en mostrar un FileMessage?

2024-08-08 01:29 UTC, criss8X commented on src/components/FileMessage.tsx
>    variant?: FileMessageVariant
Según vi abajo, metiste en el mismo 2 variantes uno para subida y otro para mostrarlo, lo planificado es que la subida del archivo se hace en el FilePreview no en el componente que va a mostrar el mensaje.

El FileMessage sólo se encarga de mostrar el mensaje de archivo con la información que devuelve Matrix sólo eso

2024-08-08 01:29 UTC, criss8X commented on src/components/FileMessage.tsx
>    progressBarState?: ProgressBarState
Esto tampoco tendría sentido en este componente

2024-08-08 01:29 UTC, criss8X commented on src/components/FileMessage.tsx
> +    return ""
Tener cuidado con estos retornos de string vacios

2024-08-08 01:29 UTC, criss8X commented on src/containers/RoomContainer/hooks/useRoomChat.tsx
> +        ? FileMessageProps
No es FileMessageProps es el FileMessageData recuerda que los clicks se gestionan en el `ChatMessages`

2024-08-08 01:29 UTC, criss8X commented on src/utils/rooms.ts
> +      return {
Espacio entre el if de arriba y este return

2024-08-08 01:29 UTC, criss8X commented on src/utils/rooms.ts
> +            throw new Error("Function not implemented.")
Arriba te puse usar FileMessageData para que aquí puedas borrar esto y no pasar información así sin nada

2024-08-08 14:23 UTC, criss8X requested changes

2024-08-08 14:23 UTC, criss8X commented on src/components/FileMessage.tsx
> +  fileUrl?: string
Aqui, fileUrl puede ser `undefined` eso es correcto, y lo ideal es que si es `undefined` el fileMessage se muestre como un error, mas adelante crearemos un componente que sea `MessageError` y sirva para cualquier mensaje y asi darle una mejor experiencia al usuario.

2024-08-08 14:23 UTC, criss8X commented on src/components/FileMessage.tsx
> +          fileUrl={fileUrl ?? ""}
Tener sumo cuidado a la hora de pasar `strings` vacios, esto aqui no debería ser asi

2024-08-08 14:23 UTC, criss8X commented on src/components/FileMessage.tsx
> +          fileExtension={getFileExtension(fileName)}
Nuevamente aqui en el `fileName` tienes ya la extension, entonces la propiedad llamada `fileExtension` es redundante, ya que internamente de igual forma podrias obtener la extension dentro de ese componente.

2024-08-08 14:23 UTC, criss8X commented on src/components/FileMessage.tsx
>            onClick={onClick}
Este `onClick` de aqui que hace? un onClick para mi en este caso es que haga click en el componente entero, pero si es hacer click en una region determinada lo mejor es especificar como por ejemplo: `onCancel`, `onAuthorClick`

2024-08-08 14:23 UTC, criss8X commented on src/components/FileMessage.tsx
>      return `${(fileSize / MB).toFixed(2)} MB`
Aqui se puede hacer un solo `return` y hacer la gestion con el operador ternario para mejor visibilidad, que crees @yurixander  ?

Si no es así marcar como completado este comentario

2024-08-09 04:13 UTC, lazaroysr96 commented on src/components/FileMessage.tsx
>    uploadProgress?: number
Resuelto, lo quite de aquí ya que lo implementé en un nuevo componente

2024-08-09 04:23 UTC, lazaroysr96 commented on src/components/FileMessage.tsx
> +  fileUrl?: string
Estuve pensando en hacer algo así, la idea que tengo es cambiar el icono de descarga por uno de error cuando no se obtenga la URL,

2024-08-09 14:07 UTC, criss8X requested changes
Esos comentarios y listo

2024-08-09 14:07 UTC, criss8X commented on src/components/FileMessage.tsx
> +  return match === -1 ? "FILE" : fileName.slice(match + 1, fileName.length)
Porque FILE con mayuscula todo si cuando le haces slice lo sacas con minuscula?

2024-08-09 14:07 UTC, criss8X commented on src/components/FileMessage.tsx
> +    />
Quitar esto de componente y ponerlo directo, ya que ahi el componente en si no tiene sentido si es 1 solo

2024-08-09 14:07 UTC, criss8X commented on src/containers/RoomContainer/ChatMessages.tsx
> +            contextMenuItems={[]}
Te falto gestionar los items del `ContextMenu`

2024-08-09 15:19 UTC, lazaroysr96 commented on src/components/FileMessage.tsx
> +  return match === -1 ? "FILE" : fileName.slice(match + 1, fileName.length)
Esto no interfiere directamente en nada, para la selección del icono el string es convertido a minúscula, para establecer la extensión en el componente, (la parte donde se muestra la extensión) el string es convertido a mayúscula, realmente se podría poner en minúscula pero no cambiaría nada, aquí el slice obtiene lo que encuentre después del último punto en el nombre del string, no necesariamente las extensiones en los nombres de los ficheros siempre son minúscula, aveses pueden ser mayúscula, todo depende del nombre que el usuario le halla dado, igual ésto no interfiere en nada, si el match no logra encontrar una extensión en el archivo devolverá por defecto FILE

2024-08-10 17:41 UTC, criss8X approved these changes

2024-08-11 00:39 UTC, yurixander approved these changes

2024-08-11 00:40 UTC, merged