feat: Implemen VideoPreview
yurixander/mirage pull request #75
Opened 2024-08-13 03:22 UTC by lazaroysr96

## Implementando VideoPreview

![imagen](https://github.com/user-attachments/assets/40600c80-4718-4a3c-89c9-d0276c9b94df)

- [ ] Implementar diseño del componente creado en Figma
- [ ] Implementar Lógica interna del Componente
- [ ] Crear un Nuevo Componente Llamado VideoMessage
- [ ] Procesar Mensajes con videos 
- [ ] Implementar Lógica para que sea posible enviar videos

2024-08-24 16:53 UTC, criss8X requested changes
Solo esos 2 detallitos minimos, todo lo demas Perfecto, buena gestion del onSend

2024-08-24 16:53 UTC, criss8X commented on src/components/VideoPreview.tsx
> +  file?: File
Preferiblemente no usar File para facilitar las pruebas a dicho componente

2024-08-24 16:53 UTC, criss8X commented on src/components/VideoPreview.tsx
> +  file?: File
Con src basta

2024-08-24 16:53 UTC, criss8X commented on src/components/VideoPreview.tsx
> +            />
Porque este img no tiene src?

2024-08-24 16:54 UTC, criss8X requested changes
Una cosa es que aqui te falta hacer la gestion de enviar ese archivo a matrix como mensaje

2024-08-26 01:41 UTC, lazaroysr96 commented on src/components/VideoPreview.tsx
> +            />
Este img forma parte del diseño original en Figma, el componente está oculto, bueno, en este último Commit lo eliminé.

2024-08-26 01:56 UTC, criss8X requested changes

2024-08-26 01:56 UTC, criss8X commented on src/utils/util.ts
> +export async function uploadVideoToMatrix(
Función innecesaria se puede gestionar dentro de sendVideoMessage

2024-08-26 01:56 UTC, criss8X commented on src/utils/util.ts
> +  console.log(uploadResponse?.content_uri)
Console.log, si estas mostrando algún error que no veo que sea el caso sería console.error

2024-08-26 03:33 UTC, criss8X requested changes

2024-08-26 03:33 UTC, criss8X commented on src/utils/util.ts
> +    const uploadResponse = await client?.uploadContent(videoFile, {
Si arriba wstaa checkeando que el cliente es nulo aquí no debería ir el `?`

2024-08-26 03:33 UTC, criss8X commented on src/utils/util.ts
> +      progressHandler: progress => {
Esto se declara pero no se está gestionando

2024-08-29 18:39 UTC, criss8X requested changes

2024-08-29 18:39 UTC, criss8X commented on src/components/VideoPreview.tsx
> +        <IoCloseCircle size={20} role="button" onClick={onClose} />
Espacio

2024-08-29 18:39 UTC, criss8X commented on src/components/VideoPreview.tsx
> +        <Button
Espacio

2024-08-29 22:42 UTC, criss8X approved these changes

2024-08-29 22:42 UTC, merged