feat: Update ChatHeader
yurixander/mirage pull request #91
Opened 2024-08-30 02:57 UTC by lazaroysr96

## Actualizando ChatHeader

### Progreso:

 - [ ] Integrar el componente a la lógica.
 - [ ] Implementar aria labels y accesibilidad (key ect...).
 - [ ] Verificar responsividad del componente usando dev tools.
 - [ ] Crear historia de storybook
 - [ ] Agregar hotkeys, tab index y event listeners de Enter para comprobar el componente en el teclado.

2024-08-31 14:13 UTC, yurixander requested changes

2024-08-31 14:13 UTC, yurixander commented on src/containers/RoomContainer/ChatHeader.tsx
> +        tooltip="Roster Expand"
```suggestion
        tooltip="Expand roster"
```

2024-08-31 15:18 UTC, criss8X requested changes

2024-08-31 15:18 UTC, criss8X commented on src/containers/RoomContainer/ChatHeader.tsx
> +          {roomDescription === undefined ? "" : "- " + roomDescription}
Ya revisaste que se pueda obtener descripcion de una Room? Porque yo creo (creeeo) que no se puede

2024-08-31 15:18 UTC, criss8X commented on src/stories/Chat/chatHeader.stories.tsx
> +    className: "flex",
Porque aquí className flex?

2024-09-01 15:54 UTC, criss8X commented on src/containers/RoomContainer/ChatHeader.tsx
> +          {roomDescription === undefined ? "" : "- " + roomDescription}
Rectifico, el asunto si esta, acabo de revisar, y pues no se esta gestionando, en este PR seria Ideal que gestiones la obtencion de el asunto, o descripcion y mostrarlo aqui

2024-09-01 15:55 UTC, criss8X commented on src/containers/RoomContainer/ChatHeader.tsx
> +          {roomDescription === undefined ? "" : "- " + roomDescription}
Gestionar cuando las descripciones son muy largas ect...

2024-09-02 00:36 UTC, lazaroysr96 commented on src/stories/Chat/chatHeader.stories.tsx
> +    className: "flex",
Es nesesario porque como tal el componente no lo implementa internamente, recibe este estilo desde fuera.

2024-09-02 00:38 UTC, lazaroysr96 commented on src/containers/RoomContainer/ChatHeader.tsx
> +          {roomDescription === undefined ? "" : "- " + roomDescription}
En el último Commit añadí esta gestión.

2024-09-02 15:45 UTC, criss8X requested changes

2024-09-02 15:45 UTC, criss8X commented on src/containers/RoomContainer/hooks/useRoomChat.tsx
> +    // eslint-disable-next-line deprecation/deprecation
porque hay una regla quitada aqui?

2024-09-02 15:45 UTC, criss8X commented on src/containers/RoomContainer/hooks/useRoomChat.tsx
> +    const roomDescription = topicEvent ? topicEvent.getContent().topic : ""
Esta gestion de pasar un string vacio esta algo rara

2024-09-08 14:03 UTC, lazaroysr96 commented on src/containers/RoomContainer/hooks/useRoomChat.tsx
> +    const roomDescription = topicEvent ? topicEvent.getContent().topic : ""
En caso de no poder obtenerse la descripción de la room sólo se muestra el título, para el caso del receptor de esta función se gestiona una determinada lógica cuando el string es igual a esto "".

2024-09-08 14:04 UTC, lazaroysr96 commented on src/containers/RoomContainer/hooks/useRoomChat.tsx
> +    // eslint-disable-next-line deprecation/deprecation
Es que ahí utilicé una función deprecada.

2024-09-08 14:38 UTC, criss8X commented on src/containers/RoomContainer/hooks/useRoomChat.tsx
> +    // eslint-disable-next-line deprecation/deprecation
Tienes que usar la función que no esta deprecada

2024-09-08 14:38 UTC, criss8X commented on src/containers/RoomContainer/hooks/useRoomChat.tsx
> +    const roomDescription = topicEvent ? topicEvent.getContent().topic : ""
Si pero no es recomendable porque más adelante igual hay que modificarlo y no se va a tener en cuenta si el string es vacío mejor usar null

2024-09-08 14:39 UTC, criss8X requested changes
Solo esas 2 cositaw

2024-09-08 20:05 UTC, criss8X approved these changes

2024-09-09 00:21 UTC, yurixander commented
@lazaroysr96 conflictos

2024-09-09 03:06 UTC, criss8X approved these changes

2024-09-09 06:55 UTC, yurixander approved these changes

2024-09-09 06:56 UTC, merged